### ISSUE TITLE
high CPU load with plugwise

### ISSUE THREAD

**Issue by napoleonmm83** [openhab/openhab#1003]
With plugwise Binding The CPU load is ~80%, without plugwise binding is ~ 30%.

In the openHAB community is also Another guy hase detail information.
http://goo.gl/2I020E

**Comment by teichsta** [comment]
so how are we going to proceed with this issue? Any suggestions?

**Comment by jowiho** [comment]
The problem still persists in 1.8. I've been playing around with the code, and the issue is indeed caused by the Quartz jobs. To be more precise: by the the SendJob.

In the current implementation, the SendJob is a single-fire job that checks if there is are messages queued in the sendQueue, and sends those messages over the serial port to the plugwise Stick. Immediately after a SendJob finishes, the SendJobListener creates a new SendJob (and a new SendJobListener). The SendJob does have some built-in pacing (through a Thread.sleep), but it's only called after actually sending a message.

So as long as there are no messages to send, the current SendJob implementation effectively is a busy loop, where new SendJobs are created and fired as fast as possible. Hence the high CPU load.

@kgoderis: if I'm reading the git history correctly, you have implemented this "busy loop" implementation of the SendJob. Was that on purpose? Wouldn't it be better to schedule a SendJob only when adding a message to the sendQueue?

I'm currently playing around with the code, trying out several solutions for the high CPU load. Once I'm satisfied with the result, I'll create a pull request.

Cheers,
Jochem

**Comment by jowiho** [comment]
I've submitted a fix in pull request https://github.com/openhab/openhab/pull/4162. It significantly reduces the CPU usage with the plugwise binding on my machine. Is anyone else able and willing to test my fix?

**Comment by markwegman** [comment]
I tested @jowiho's pull request in my setup with 7 Circles. Power usage updates are processed correctly and timely (10-15 second interval in my config) with no noticeable increase in CPU usage. It has been running stable for a couple of days now.
