### ISSUE TITLE
Problems with http out binding 

### ISSUE THREAD

**Issue by benderl** [openhab/openhab#1133]
Hi!
I am new to openHAB and trying to connect my homematic devices with a dimplex heatpump. The Heatpump has a network connection and can be queried by simple get requests. Reading values with the http binding works already, but writing changes back is my current problem.

For example I defined one item as a number with the following binding config:
```
{ http=">[*:GET:http://heatpump/usr-cgi/query.cgi?var%%7cI%%7c16%%7c%2] <[http://heatpump/usr-cgi/xml.cgi?I%%7c15%%7c15:60000:REGEX(.*?<VALUE>(.*?)</VALUE>.*)]" }
```

The heatpump expects some pipes "|" in the URL so I encoded them with "%%7c". Receiving values works like a charm, but if I try to modify the item, I get the following error in the debug log:

```
TRACE o.o.b.h.internal.HttpBinding[:276] - doesn't find matching binding provider [itemName=WPM_Test_Partystunden, command=CHANGED]
```

I have some experience in programming, but not with Java. I tried setting up a IDE as described, but eclipse 4.2.2 seems to be very unstable on my Kubuntu 14.04 and crashes. So learning and debugging is very frustrating for me now. Maybe someone can help me here?

Regards,
Lutz

p.s.: I had opened a threat on G+ some days ago with the same topic which I have closed now.

**Comment by benderl** [comment]
This issue is resolved with Pull Request #1990 .

**Comment by teichsta** [comment]
Thanks for the Update!

**Comment by DidiDimp** [comment]
Hello benderl,
I have the same problem. I tried to connect my Dimplex heat pump to OpenHab
What is the right Syntax for reading an writing values?

Thanks in advance

Jean-Marie

**Comment by benderl** [comment]
Hello Jean-Marie,
I use this syntax for the item definition.
`Number	WPM_Urlaubstage "Anzahl Urlaubstage [%d d]" <calendar> (gWPM,gLog) { http="<[WPMCacheInteger:120000:REGEX(.*?<INDEX>16</INDEX>\\n\\t*<VALUE>(.*?)</VALUE>.*)] >[*:GET:http://heizung/usr-cgi/query.cgi?var%%7cI%%7c16%%7c%2$s]" }`
The reading (<) is done with a cached page. Syntax for writing the new value is after the ">".
The definition for the cached page is in the openhab.conf:
`http:WPMCacheInteger.url=http://heizung/usr-cgi/xml.cgi?I%%7c1%%7c207
http:WPMCacheInteger.updateInterval=60000 
http:WPMCacheAnalog.url=http://heizung/usr-cgi/xml.cgi?A%%7c1%%7c207
http:WPMCacheAnalog.updateInterval=60000
http:WPMCacheDigital.url=http://heizung/usr-cgi/xml.cgi?D%%7c1%%7c207
http:WPMCacheDigital.updateInterval=60000`

Lutz

**Comment by DidiDimp** [comment]
Thank you benderl for the quick reply.

I am using Openhab 2
I still can not see the Data from the Dimplex.

Is you sitemap and items file available for download?

Thanks in advance

**Comment by benderl** [comment]
Please find my item file and a testing sitemap attached.
What type of controller does your heatpump have? Which firmware version?
[heatpump.zip](https://github.com/openhab/openhab/files/193925/heatpump.zip)

**Comment by DidiDimp** [comment]
Thank you for the file.
you did a great Job.

It is no way to make it running on Openhab 2

II have also installed Openhab 1.8.2 , ther  it runs without any problem .

I have the firmware version A.1.5.0
I also tested it on my brothers Heatpump with the firmware  A1.4.9,  on this heat pump some indexes are not correct.

finaly i looked in the logfile of OH2

There I found the following error messages
java.lang.IllegalArgumentException: given transformation function 'REGEX(.*?<INDEX>1</INDEX>\n\t*<VALUE>(.*?)</VALUE>.*)]' does not follow the expected pattern '<function>(<pattern>)'
	at org.openhab.binding.http.internal.HttpBinding.splitTransformationConfig(HttpBinding.java:231)[171:org.openhab.binding.http:1.9.0.201603280113]
	at org.openhab.binding.http.internal.HttpBinding.execute(HttpBinding.java:181)[171:org.openhab.binding.http:1.9.0.201603280113]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:157)[158:org.openhab.core.compat1x:2.0.0.201603280103]
2016-03-29 21:13:26.103 [WARN ] [.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type REGEX
2016-03-29 21:13:26.104 [WARN ] [ab.binding.http.internal.HttpBinding] - couldn't transform response because transformationService of type 'REGEX' is unavailable

Is it a syntax error or a OH2 http bindinmgs error?

**Comment by benderl** [comment]
I did not do any tests with OH2. But I think regular expressions should be supported. Maybe the syntax has changed?
Reverse engineering the indexes was a nightmare. At least most are somehow documented in the dimplex wiki of the KNX module. There are different controllers with different indexes but the way to get them is the same.

**Comment by DidiDimp** [comment]
Hy benderl

I, am now a step further.

I can see in the log file that values are imported.

No i have further errors.
I think all map files are missing on your posted Zip file

</VARIABLE>
</ANALOG>
</PCO>
</PCOWEB>
 to <PCOWEB>
<PCO>
<ANALOG>
<VARIABLE>
<INDEX>1</INDEX>
	<VALUE>23.0</VALUE>
</VARIABLE>
.
.
.<VARIABLE>
<INDEX>207</INDEX>
	<VALUE>U</VALUE>
</VARIABLE>
</ANALOG>
</PCO>
</PCOWEB>


2016-03-30 15:21:59.146 [WARN ] [ab.binding.http.internal.HttpBinding] - couldn't transform response because transformationService of type 'REGEX' is unavailable
2016-03-30 15:21:59.151 [WARN ] [.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type REGEX





Caused by: java.io.FileNotFoundException: /opt/openhab2/conf/transform/wpm_out.map (Datei oder Verzeichnis nicht gefunden)
Caused by: java.io.FileNotFoundException: /opt/openhab2/conf/transform/wpm_modus_de.map (Datei oder Verzeichnis nicht gefunden)
2016-03-30 15:11:15.057 [ERROR] [ui.internal.items.ItemUIRegistryImpl] - transformation throws exception [transformation=org.eclipse.smarthome.transform.map.internal.MapTransformationService@107611f, value=-]
org.eclipse.smarthome.core.transform.TransformationException: An error occured while opening file.


Hope you have a wonderfull day

Jean-Marie

**Comment by benderl** [comment]
Yes I forgot the map files and some rules for number conversion. The attached file should contain everything needed. The problem with the variable indexes can be because of another firmware. There are two versions: J/L and H. Have a look at the [Dimplex Wiki for the NWPM](http://www.dimplex.de/wiki/index.php/NWPM). I have the J/L software on my controller.
[Heatpump.zip](https://github.com/openhab/openhab/files/198231/Heatpump.zip)

**Comment by DidiDimp** [comment]
Thank you benderl,
everything is working now. The only thing i have to do is to crea´te custom icons.

Hope you have a wonderful Day

Jean-Marie

**Comment by benderl** [comment]
I attached my custom icons.
[heatpumpicons.zip](https://github.com/openhab/openhab/files/201244/heatpumpicons.zip)

Do you think you could code a binding for our heatpump? I am not really satisfied with this mix of http items and rules. But anyway I will move to a new location this year and there will probably be no heatpump anymore. So I could only help as long as I stay in my current home.
