### ISSUE TITLE
Zwave new devices for database

### ISSUE THREAD

**Issue by Gilles76** [openhab/openhab#1139]
Hi Chris,

Here is some new devices:

Aeon labs, id9, type 2 => Home Energy Meter (2/3 clamps),
http://www.pepper1.net/zwavedb/device/65 ,
http://www.pepper1.net/zwavedb/device/65/65-0086-0002-0009-03-02-61-03-38.xml

Manufacturer 138, id100, type d => benext Built-in Dimmer, manual in
copy + xml find from OZW => in you PM

manufacturer 132,id 109, type 311 => fortrezz SSA1 /SSA2 ,
http://www.pepper1.net/zwavedb/device/294 ,
http://www.pepper1.net/zwavedb/device/294/294-0084-0313-0108-00-02-61-00-00.xml

Thank you,

Gilles.

**Comment by cdjackson** [comment]
Hi Gilles,
Can this be closed?
Chris

**Comment by Gilles76** [comment]
Hi Chris, 

Happy new year as I don't write you in january.

I'm afraid you can't close this issue. You hav to tell me.

Every thing is ok, but when you choose in habmin, Hem then association group then group 1 (it's the one I use), I can see twice my primary none which is the member one.

If I click on my 71 node it's ok, if I click on the second 71 the blue line goes on the next node.

So HEM is ok, it's working, but twice in association group. What do you want to do ? Another issue ?

heers,

Gilles.

**Comment by cdjackson** [comment]
Hi Gilles,
Yes - happy new year :)

I think this might be an issue with HABmin rather than the database. If I understand you correctly, you now have two controllers showing in HABmin? I’m not sure I undestand so maybe you can provide a picture or two and then we can work out what to do (either another issue if it’s the binding, or an issue in HABmin)...

Thanks
Chris

**Comment by Gilles76** [comment]
![double_node_hem](https://cloud.githubusercontent.com/assets/7738873/5710291/34aa89fc-9aa1-11e4-9705-727ad065b4ab.jpg)
![node_not_totally_close](https://cloud.githubusercontent.com/assets/7738873/5710292/34ad4868-9aa1-11e4-9574-448542866e35.jpg)
First you can see double node, then second image, when I click on minus, it's not totally reduce.

**Comment by cdjackson** [comment]
This might be a binding issue… What is node 71? Is it a node that doesn’t exist anymore?

**Comment by Gilles76** [comment]
Argh not a ghost node but my controller node. :)

**Comment by cdjackson** [comment]
Ah - so node 71 is your main controller used with OH (the UZB?)?

Regarding the RPi - I know you’re not using the RPi - I was just asking about your logs as I remember that you had some duplication of messages in one of your logs a while ago. I found that this problem is not just an RPi problem, but maybe also happens a small amount on other computers… Anyway - I have your logs - thanks - is this with the very latest binding (from yesterday or today)?

Merci :)

**Comment by Gilles76** [comment]
Ha ok for RPI ;0)

I'm using binding from github which is : 1.7.0.201501112326

Tomorrow I will see with a cubieboard 2.

**Comment by cdjackson** [comment]
> On 12 Jan 2015, at 20:55, Gilles76 <notifications@github.com> wrote:
> 
> I'm using binding from github which is : 1.7.0.201501112326
> 
Perfect - thanks.

**Comment by cdjackson** [comment]
Bonjour Gilles,
Can I suggest that close this issue since all the devices are now added (right?). Then if you want we can add another issue for the duplicate node in the association group issue...

Chris

**Comment by Gilles76** [comment]
Hi Chris,

Sorry for my silence, I retrive my adsl access.

Yes we can close this issue and open another one for double node.
