### ISSUE TITLE
Fritzbox binding: hangs on inbound calls if  calling number is supressed 

### ISSUE THREAD

**Issue by jotwg** [openhab/openhab#1220]
openHAB version: 1.5.0, if a call comes in w/o calling  number the fb  binding seems  to stop working: no further  events are seen by my rules, need to stop/Start the binding service on osgi  console.

**Comment by Dennis650** [comment]
Hi,

tested with 1.7.0. This bindings still works after calls without calling numbers.

I think the issue can be closed.

Greetings
Dennis

**Comment by jotwg** [comment]
Hi,

unfortunately not: tested with 1.7.0-snapshot as of today -> fb binding still hangs when incoming call w/o calling number gets disconnected.

Here are the relevant parts of my config:
---------------
item:
Switch Incoming_Call         "Ringing"             (Phone)    { fritzbox="inbound" }

rule:
rule "Incoming call"
when
        Item Incoming_Call received update
then
        var String  regexp  = "(.*?VALUE=\")(.*?)(\">.*)"
        var Pattern pattern = Pattern::compile(regexp)
        var Matcher matcher
        logInfo( "FILE", "Incoming_Call.state: " + Incoming_Call.state.toString())
        if ( Incoming_Call.state.toString() == "ON" ) {
                     :
---------

Seems that the fb binding hangs when trying to access Incoming_Call.state.toString(). Everything works fine if a calling number is present...

Thx.
jotwg

**Comment by J-N-K** [comment]
You are both right and wrong. The binding is broken for incoming calls without caller number, if you use

Call    Incoming_Call_No                "Anrufer [%2$s]"                        (gPhone)        { fritzbox="inbound" }

in that case, the binding fails to fill the item with correct values, because the external number is empty. 

But the binding is working perfectly fine if you use

Switch  Ringing                               "Klingel"               (gPhone) { fritzbox="inbound" }

because the external number is not used in that case. 

This part can easily be fixed, I would like to have an advice if the number should be replaced with a "unknown", "suppressed", 0, space or whatever. Keep in mind that some users might prefer other languages than english.

Another issue is that if you define two or more items with { fritzbox= "inbound"}, only one will work. I will invesitgate that further and open another issue for that.

**Comment by J-N-K** [comment]
After some further investigation: I cannot reproduce the error anymore. That seems strange, as I have seen it. The error occired in l545, when the new CallType object is instantiated. However the CallType constructor can handle the empty string.  Somehow one of the parameters had a null value, which I cannot explain from the source code.

Could you please post your full configuration with all items that use the binding. Do you use any kind of persistance service for these items?

**Comment by jotwg** [comment]
Sorry, forgot this...

Some quick answers to your questions above:
- indication string in case of missing calling number: I would propose "anon."
- persistance service: I'm not using any persistance service on this item

More to follow, hope I can post my full configurations soon...

Thx!

**Comment by hmerk** [comment]
closed due to lack of activity
