### ISSUE TITLE
How to send out & receive a simple string cmd via TCP binding?

### ISSUE THREAD

**Issue by cyberrob** [openhab/openhab#1322]
I've defined 2 items. TcpServer for listening, TcpClient for sending cmd.

````
String TcpServer "Tcp server receive: [%s]" <bath> (Office_Desk) { tcp="<[127.0.0.1:25001:'REGEX((.*))']"}
String TcpClient "Tcp client sent cmd: [%s]" <boy0> (Office_Desk) { tcp=">[192.168.1.236:6969:'HELLO_FROM_OPENHAB!']"}
````
I use nodejs as server for openhab to connect, which seems ok only without cmd sent from client:
````
-> % node tcp_server.js
CONNECTED: 192.168.1.84:47485
CLOSED: undefined undefined
CONNECTED: 192.168.1.84:47488
````
If using nodejs as client to connect openhab server(192.168.1.84:25001):
````
-> % node tcp_client.js
Connected to 192.168.1.84:25001
error: Error: read ECONNRESET
Conenction closed
````
And the openhab said:
````
08:26:54.594 INFO  o.o.b.t.AbstractSocketChannelBinding[:1240] - We will accept data coming from the remote end /127.0.0.1:25001
08:27:07.393 INFO  o.o.b.t.AbstractSocketChannelBinding[:1360] - Received connection request from /192.168.1.236:52342
08:27:07.398 INFO  o.o.b.t.AbstractSocketChannelBinding[:1447] - Disconnecting the unallowed remote end /192.168.1.236:52342
````
Connection made and reset immediately! nodejs connect openhab via 25001, Why is it a `unallowed` remote end? How to keep it connected?

Another question is how should I send out cmd or print out received cmd? Say sending some simple string communicating.

**Comment by waconiglio** [comment]
I can vouch for this behavior. I am trying to do exactly the same duplex communication using a Python program and can't seem to get OpenHAB to accept a TCP connection.

**Comment by Nebula83** [comment]
I appears to be that one has to set the listening port in config (tcp:port=25001) and then set 

String TcpServer "Tcp server receive: [%s]" <bath> (Office_Desk) { tcp="<[127.0.0.1:*:'REGEX((.*))']"}
(replaced 25001 by *) 

What I think happens is that the binding filters on the client port rather than the server port. The server listens for clients at 25001 but client connect via random free ports (this is normal TCP behavior). Therefore instead of accepting the client because it connected via port 25001, it uses the connected port (in this case 52342) which will never match unless you are very lucky.

In my case I can;t even get the inbound server to listen via the binding: I have to set it in config therefore limiting the amount of TCP and UDP server to one each.

**Comment by hmerk** [comment]
closed due to lack of activity
