### ISSUE TITLE
Chart not working

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab#1325]
Hi,

I just installed java 8 and openhab 1.5 stable according to the apt-wiki page on BananaPI. All working fine except persistence:
data surely is persisted as it should (using RRD4J) but /chart-servlet displays empty chart. /rrdchart.png works fine.

I could not see any pointers with debug mode enabled. What can I do to debug this?

Thanks!

**Comment by sercasyr** [comment]
It also happens to me from time to time. 
I have several persistence strategies, and some of them don't allow me to show graphs in some times. 

I have never been able to find a "cause-effect" link between a particular strategy and a wrong graph, but I have been having a lot of problems with these, and I usually end up using the every minute strategy   "everyMinute:	"0 0/1 * * * ?"   because when I mix everyUpdate with fixed-frequency strategy I tend to have lots of problems with the graphs...

**Comment by mrguessed** [comment]
Other than persistence, a Chart may not render if one-or-more Items in the Chart-Group have the same Item Label.

Given the Item definitions, with both Items labelled _`Ambient`_:
```
Group GTemperatureChart (GAll)

...
Number   NestTStatDownstairs_ambient_temperature_f "Ambient [%.1f °F]" <temperature>       (GThermostatDownstairs,GTemperature,GTemperatureChart) {nest="<[thermostats(Downstairs).ambient_temperature_f]"}
Number   NestTStatUpstairs_ambient_temperature_f "Ambient [%.1f °F]" <temperature>         (GThermostatUpstairs,GTemperature,GTemperatureChart) {nest="<[thermostats(Upstairs).ambient_temperature_f]"}
```

and the SiteMap snippet:
```
Frame {
   Switch item=TemperatureChartPeriod label="Chart Period" mappings=[0="Hour", 1="Day", 2="Week"]
   Chart item=GTemperatureChart period=h refresh=6000 visibility=[TemperatureChartPeriod==0, TemperatureChartPeriod=="Uninitialized"]
   Chart item=GTemperatureChart period=D refresh=36000 visibility=[TemperatureChartPeriod==1]
   Chart item=GTemperatureChart period=W refresh=36000 visibility=[TemperatureChartPeriod==2]
}
```

and the `rrd4j.persist`:

```
Strategies {
        // for rrd charts, we need a cron strategy
        everyMinute : "0 * * * * ?"
        everyDay : "0 0 23 * * ?"
}

Items {
        SystemDataVersion, SystemUserDataDataVersion, SystemTimeStamp, SystemLocalTime, SystemLoadTime : strategy = everyDay
        GPersist* : strategy = everyChange, everyMinute, restoreOnStartup
        GTemperature* : strategy = everyMinute, restoreOnStartup
}
```

Then the chart won't render under openHAB 1.6.2.  Simply change _one_ of the Item labels from _`Ambient`_ to something else, and the chart will display.

NB: Posted for discovery, since the behaviour is the same as the initial post (an empty chart image from `http://localhost:8080/chart?groups=GTemperatureChart&period=h&random=1`)

**Comment by sercasyr** [comment]
It's not my case. I don't repeat labels...

Persistence and graphs have always behaved weird in my OpenHAB systems.

**Comment by spodg** [comment]
I had similar problem and solution was I had to delete demo.sitemap and demo.items and demo.* everything, some how my sitemap (with corresponding files) was conflicting with demo files. I suspect due to the same group names in different sitemaps. Once I deleted demo files, charts started working, items stopped duplicating.

**Comment by ssalonen** [comment]
I switched to influxdb but still had issues with the chart. The issues started when I tried rrd4j, and they did not go away even when I switched to db4o. Everytime I changed the default persistence provider in openhab cfg.

This is how I fixed it:
Renamed identical labels (as discussed in this thread) -- no immediate change.

I had configurations/persistence/rrd4j.persist.old that seemed to  be active still (new rrd4j files were generated under etc). I just removed the rrd4j plugin and the "persist.old" and, boom!,  chart started to work immediately.

Hope this helps

**Comment by teichsta** [comment]
@cribskip did you solve this issue meanwhile? Does any of the workarounds being discussed here helped? Would be breat if you could comment briefly …

**Comment by cribskip** [comment]
Meanwhile, I switched to Raspberry PI 2. No problems at all concerning persistence.
Shall we close this?

**Comment by teichsta** [comment]
yes, please!

**Comment by substatica** [comment]
Renaming identical labels solved this for me with MySQL persistence.
