### ISSUE TITLE
Opt-out for fritzbox-binding telnet usage on branded boxes

### ISSUE THREAD

**Issue by kwave** [openhab/openhab#1378]
The fritzbox binding uses - amongst others - telnet to connect to the fritzbox. Many branded fritzboxes (e.g. KabelBW in Germany) do not allow to enable telnet. A configuration property which disables the telnet access (and of course also limits the feature set of the binding) would be great.
For monitoring incomming calls, there is a call monitor service on port 1012, which is also available for branded boxes.

**Comment by staehler** [comment]
It seems that AVM (producer of fritzbox) decided to close the telnet port with the next firmware update.
http://www.heise.de/netze/meldung/Testversion-Fritzbox-Firmware-fuer-Vectoring-und-ohne-Telnet-2696116.html (german article about that)
Would be really great if someone can find a workaround, otherwise further firmware updates lead to openhab incompatibility :-1:

**Comment by hmerk** [comment]
can be closed as we have a fritzboxTR064 binding not using telnet.
