### ISSUE TITLE
Additional states for Philips Hue lights

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab#2020]
The Philips Hue API supports additional states, which are currently not implemented in openHAB: alert, effect and transitiontime. (see http://www.developers.meethue.com/documentation/lights-api)

It would be great if these states could be also triggered from openHAB.
Especially the transitiontime would be useful, as this allows smooth transitions of the light state (e.g. brightness) without manually programming loops in openHAB.

If anybody has an idea how to implement the transition time in openHAB, so it can be triggered from a rule (with sendCommand?), I could try to implement it.

**Comment by polarathene** [comment]
@teichsta Chiming in here for this support as well. I'm new to Java but have experience with many other languages, I'd be happy to help create PRs for the additional support but require some guidance/advice on how to approach. 

- Is the binding in this repo for hue the same as used for OH2 or only OH1?
- Do any changes need to be made for OH2 to add this support?(such as refactor)
- Are there any blockers preventing this additional support, or do I just need to add additional REST requests and functions/logic(presumably existing features are like this and I could use them for referrence).

I'm also interested in supporting Groups defined via the Hue Bridge, which are more effective for control than the group system openHAB provides(other discussions around this involve lights being updated one at a time instead of all lights belonging to a group in parallel.

**Comment by kaikreuzer** [comment]
As this request is from Jan 2015, I doubt that anyone will implement it on 1.x.
Efforts should be put on https://github.com/eclipse/smarthome/issues/1722 instead.
