### ISSUE TITLE
mapping for Selection Item with Yamaha binding does not work as expected

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#2048]
The yamaha-binding uses two string Items for switch through sources and DSP-Programs. But this doesn't work as expected, because there are programs with spaces in name, and there is a source called "V-AUX" which can't be selected with Selection Item. 
A definition like:

    Selection Item Yamaha_Source mappings=[AV5="AV5",AV6="AV6","V-AUX"="V-AUX"] 

lists all Items, but I can't change Source to V-AUX. Same for DSP:

    Selection Item Yamaha_DSP mappings=["2ch Stereo"="2ch Stereo","Sci-Fi"="Sci-Fi",Adventure="Adventure",Drama="Drama"] 

shows 4 Selections, but only the third and the fourth works as expected.

**Comment by udo1toni** [comment]
Has none other this problem?

**Comment by teichsta** [comment]
Hi Udo,

better ask those question on the Google Group before opening an issue (see also https://github.com/openhab/openhab/wiki/How-To-Contribute) since i bet the response time there is shorter. Once you are sure you've found an issue please feel free to open an issue for that.

So in this case announce the problem on the Group and refer to this issue.

Best, Thomas E.-E.

**Comment by udo1toni** [comment]
Possible same as https://github.com/openhab/openhab/pull/2880...

**Comment by udo1toni** [comment]
Tonight I could verify that the Error has gone with the Nightly 1.8.0-997 (with Fix for #2880)
