### ISSUE TITLE
ANEL-Binding: NET-PwrCtrl HOME not supported

### ISSUE THREAD

**Issue by klakra** [openhab/openhab#2068]
I recently tried to connect my NET PwrCtrl **HOME** to openHAB via the ANEL binding. Unfortunately there seems to be a difference in the data structure of the HOME version compared to the HUT version which was used as reference model and so I get the following error message in the openhab.log:

*13:03:06.036 [ERROR] [a.internal.AnelConnectorThread:267 ] - Error occured when received data from Anel device: 192.168.10.9
java.lang.IllegalArgumentException: Data with 26 values expected but 16 received: NET-PwrCtrl:NETPWRCTRL :192.168.10.9:255.255.255.0:192.168.10.1:0.4.163.18.1.12:IP-Cam,0:HomeMatic CCU,1:Synology DS,1:Nr. 4,0:Nr. 5,0:Nr. 6,0:Nr. 7,0:Nr. 8,0:248:80*

Reference data structure HUT model:
*NET-PwrCtrl:(Name):(I.P):(M.A.S.K):(G.a.t.e.w.a.y):(M.A.C):(8x Relay Name + State):Locked_Sockets:HTTP-Port:(8x IO Name + State):Temperature:Firmware_Version:(0x0D)(0x0A)*

Data structure HOME model:
*NET-PwrCtrl:(Name):(I.P):(M.A.S.K):(G.a.t.e.w.a.y):(M.A.C):(8x Relay Name + State):Locked_Sockets:HTTP-Port*

I assume the data structure of the reference model is valid for the versions with IO-ports (HUT and IO) and the data structure of the HOME model is valid for the versions without IO-ports (HOME and PRO). I have no idea about the ADV version, because this model has no IO-ports but changeable HTML like e.g. HUT.

**Comment by paphko** [comment]
Unfortunately, the reported UDP package does not comply to the format specified by the manufacturer: http://www.anel-elektronik.de/forum_neu/viewtopic.php?f=16&t=207#p574

It will hopefully be sufficient to adjust the AnelDataParser class to handle both types of UDP package formats. The IO and temperature will then be unset (maybe other parts must be adjusted to handle unset fields) and should not be used.
If IO commands are sent by some rules, there should not be any consequences because the device should simply ignore them.

**Comment by teichsta** [comment]
Bugfix has been merged into master (see #2075)
