### ISSUE TITLE
Zwave - error handling of a failed node does not display unknown status in the GUI

### ISSUE THREAD

**Issue by moritzthecat** [openhab/openhab#2081]
the error handling of the status info in the GUI is not clear to me.

when a node cannot be reached any more and sending data to this node fails then the GUI still shows on/off status as if it would be alive and properly switching. Although the log clearly shows this node is failing:

2015-02-04 19:55:47.633 [ERROR] [b.z.i.p.s.SendDataMessageClass] - NODE 4: Got an error while sending data. Resending message.
2015-02-04 19:55:55.897 [WARN ] [i.p.s.IsFailedNodeMessageClass] - NODE 4: Is currently marked as failed by the controller!
2015-02-04 19:56:11.934 [ERROR] [NodeNeighborUpdateMessageClass] - NODE 4: NodeNeighborUpdate FAILED
2015-02-04 19:56:12.567 [WARN ] [b.z.i.p.s.SendDataMessageClass] - Already processed another send data request for this callback Id, ignoring.
2015-02-04 19:56:19.688 [ERROR] [NodeNeighborUpdateMessageClass] - NODE 4: NodeNeighborUpdate FAILED

Config is openhab 1.6.2 with Zwave binding 1.6.2
Classic UI, BananaPi, Debian
Device tested: is a Fibaro Switch FGWPE/F-101 - the item definition looks like this
Switch Coffee_Kitchen_Switch "Coffee machine" (GF_Kitchen) {zwave="4:command=switch_binary"}

**Comment by cdjackson** [comment]
> the error handling of the status info in the GUI is not clear to me.
> 
> when a node cannot be reached any more and sending data to this node fails then the GUI still shows on/off status as if it would be alive and properly switching. Although the log clearly shows this node is failing:
> 
This is correct - there is no option within openhab to provide an indeterminate state, so the binding has no ability to do anything different.

**Comment by moritzthecat** [comment]
maybe my wording is not right naming it as an unknown signal...
but error handling of bi-directional wireless IoT protocols should be at a priority to the underlying openhab architecture. At least the zwave binding supports the recognition of data transfer errors already (cf. above lof extract) as they are written to the log.
If openhab bus architecture does not support handling of failed data transmissions yet it should be a priority to add this feature in the future.

**Comment by cdjackson** [comment]
I agree that this is a missing feature of openhab - or probably more correctly the esh core. It mught be worth raising this as an issue in esh?


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: moritzthecat <notifications@github.com> </div><div>Date:05/02/2015  21:20  (GMT+00:00) </div><div>To: openhab/openhab <openhab@noreply.github.com> </div><div>Cc: Chris Jackson <chris@cd-jackson.com> </div><div>Subject: Re: [openhab] Zwave - error handling of a failed node does not
  display unknown status in the GUI (#2081) </div><div>
</div>maybe my wording is not right naming it as an unknown signal...
but error handling of bi-directional wireless IoT protocols should be at a priority to the underlying openhab architecture. At least the zwave binding supports the recognition of data transfer errors already (cf. above lof extract) as they are written to the log.
If openhab bus architecture does not support handling of failed data transmissions yet it should be a priority to add this feature in the future.

**Comment by cdjackson** [comment]
I think you raised this as an issue in the group. I would suggest closing this issue and either raising something in ESH or openHAB2 forums?
@teichsta do you agree?

**Comment by teichsta** [comment]
hmm … i am not sure. We could change the state to UNDEF when the underlying node disappeared, right? I agree there is no "inactive" state of a switch widget currently, so ultimately it makes no difference to the user but at least the platform would know the right status, wouldn't it?

**Comment by cdjackson** [comment]
The 'platform' (I guess you mean the binding?) does know the correct status (as per the log) - the issue I think that's raised is that there's no way to provide an indeterminate state in the GUI to show that a device has 'gone away' (other of course than displaying this as an item).

My point though was that there's no way to show this in the GUI in OH1 (I think?). I do think that some discussion on the topic might be useful as I think this is something that is missing, but as we can't do anything about it in OH1 I wanted to close and suggest to the OP that this be raised elsewhere?

Up to you - I'm happy to leave this open, but as I don't think that it's a zwave issue there's not much I can do about changing the core unless you can suggest something?

**Comment by mrguessed** [comment]
Does the Binding provide a facility to bind an Item against the Error-state of the [Z-Wave] Device?

If so, then you're down to how to present [in the UI] this information, along with any Rules that people might want to run against it.

I'd hate to see the Item value/state get subverted to do this task.  In my binding I still have the value, albeit dated, since the downstream system still supplies it for "broken" Devices.

Actually, I have a whole bunch of these attributes (and statistics) that the downstream system is providing, and they can all be bound.  The downside to this model is that [in practice] it requires generators (Item and Sitemap) to make it useful/manageable to the end-user.

The other downside is that some of the Sitemap dynamic attributes, _Color_, aren't adhere'd to by all clients and we're missing others like _Enabled_.

**Comment by cdjackson** [comment]
> Does the Binding provide a facility to bind an Item against the Error-state of the [Z-Wave] Device?
> 
Yes - there’s a host of information (including if the device is dead) that can be derived about the state of the node - it’s all in the Wiki...

> If so, then you're down to how to present [in the UI] this information, along with any Rules that people might want to run against it.
> 
True, but I personally think that it would be useful to have a standard way of doing this without binding another item. My preference was to have (possibly user defined) attributes to add additional data to an item, rather than having to define new items for every piece of information….


> Actually, I have a whole bunch of these attributes (and statistics) that the downstream system is providing, and they can all be bound. The downside to this model is that [in practice] it requires generators (Item and Sitemap) to make it useful/manageable to the end-user.
> 
This is the same for the zwave binding. 


> The other downside is that some of the Sitemap dynamic attributes, Color, aren't adhere'd to by all clients and we're missing others like Enabled.
> 
The dynamic sitemap stuff is reasonably new (ok, about a year old). I added all this when I moved over from Vera, and implemented it into the ClassicUI, and Victor put it into HABDroid, but Mikhail has gotten busy so didn’t update GreenT


I think we’re getting off topic anyway - I’m not asking to add anything new, or change the way this is done. All I was saying is that there’s nothing I can do in the zwave binding, and if the person who raised this wants to discuss it further, then it should be taken elsewhere (or a separate issue raised).  I just wanted to close the open issue against the zwave binding - alternatively, if someone has an idea for something new in the binding, then I’m happy to look at adding it?

**Comment by teichsta** [comment]
> I think we’re getting off topic anyway

**Comment by teichsta** [comment]
so, i'll close this issue for now and would be happy to discuss anything else on the Maillinglist.

Thanks, Thomas E.-E.

**Comment by cdjackson** [comment]
Thanks Thomas.

**Comment by mrguessed** [comment]
> Yes - there’s a host of information (including if the device is dead) that can be derived about the state of the node - it’s all in the Wiki...

Then, to handle the original request, you could just post an example of what they'd need to do in the Item repo, and in the Sitemap, to display the  "Error" status.

Right now, it's left dangling (even if Thomas has closed the issue)...  The next person that has the same question will be left with no answer.

And yes, I believe there needs to be a broader (non ZWave-specific, not here) discussion on what really should be done.
