### ISSUE TITLE
PLCBus house code / unit code addressing bug 

### ISSUE THREAD

**Issue by renescherer** [openhab/openhab#2098]
The 1.6.2 version of the PLCBus binding has a bug in the way house codes and unit codes are packed into a single byte. The 4 bit house code has to be packed into the 4 most significant bits of the address byte.
At the moment the code only works for devices in house code A.

The 2 lines which need changing are 128 and 145 in DataFrame.java:
Line 128: result.add(Convert.toByte((home << 4) | unit));
Line 145: home = data[1] >>> 4;

**Comment by teichsta** [comment]
Hi @renescherer thanks investigating and letting us know. Any chance to create a PR with your proposed Fix? Best, Thomas E.-E.

**Comment by renescherer** [comment]
Hi @teichsta 
I'm happy to do that but I might need a few hints getting started. I'm new to git and I'm not quite sure what I would need to do.

Thanks,
Rene

**Comment by teichsta** [comment]
does the Github docs help?

https://help.github.com/articles/creating-a-pull-request/

**Comment by brunodom** [comment]
Hi folks,
I found the same problem and also I made some changes in binding that I'm using to support 3-phase instead of 1-phase. I'll be more than happy to submit this change as soon I made it in a descent way :).
BTW: Do you guys knows any workaround on how pooling PLCBus units in order to chack their status? Also, I didn't invest time yet, but dimmer is only working on ClassicUI, do you know why? any guess? 

Best Regards!
-Bruno Domingues

**Comment by renescherer** [comment]
I've submitted PR https://github.com/openhab/openhab/pull/4197 for this fix.

**Comment by teichsta** [comment]
#4197 has been merged into master and 1.8
