### ISSUE TITLE
Group charts require unique labels for all items

### ISSUE THREAD

**Issue by tsadowski** [openhab/openhab#2199]
Hi,

I had trouble making charts from groups:

2015-02-26 20:00:40.420 [DEBUG] [ui.internal.chart.ChartServlet] - Illegal argument in chart: {}
java.lang.IllegalArgumentException: Series name >Raumtemperatur < has already been used. Use unique names for each series!!!

This is as far as I know not mentioned in the documentation. It is also the only situation where a label needs to be unique. Would it be possible to create the charts based on the item id which is unique anyway and just add a label later?

Cheers, Torsten 
##

**Comment by teichsta** [comment]
corresponding discussion on Google Group: https://groups.google.com/forum/#!topic/openhab/-DoMOHziw8E

**Comment by teichsta** [comment]
hmm … afaiu the code (RRD4JChartServlet.addLine and DefaultChartProvider.addItem) it differentiates between Item Names and Item Labels (for the legend). 

@cdjackson could you probably shed some light on this?

**Comment by cdjackson** [comment]
I'm not so sure. I didn't check rrd, but it looks like in the default provider it uses the labels. It's been a while since I looked at this, but I have a feeling that xchart doesn't (or didn't when I wrote this 18 months ago) provide the option to have separate labels and IDs.

Using item names is not very nice, although admitedly it does ensure uniquness. Of course, if you have the same label, then you can't tell the difference between plots anyway!

I'll have a look at this - maybe I can detect if the same label is already used an add a '(2)' to the end of the label.

**Comment by 9037568** [comment]
I don't see a PR for this. @steve-bate have I overlooked it?

**Comment by steve-bate** [comment]
I must have misread the related issue link as a PR. I've updated the labels. Thanks for catching that.

**Comment by danielo515** [comment]
I was also affected by this issue. I don't understand why a label needs to be unique.

**Comment by tkuehne71** [comment]
This seems to be triggered somehow. After adding a bit of configuration to my items and sitemaps, all of a sudden this error pops up for all charts in my configuration that have multiple items grouped together to display in a chart. None of the items have identical labels, btw. I found this issue in 1.8.3.

**Comment by tkuehne71** [comment]
Found my trigger. I had a second file in my items directory called "bla-save.items", that I had in there as a backup. Since the file still had the ".items" extension, openhab read all the items in there and that's where the identical names came from, that threw off the chart provider. Deleting that file fixed my problem.

**Comment by 9037568** [comment]
The ChartServlet is now in [ESH](http://github.com/eclipse/smarthome/), so this can no longer be fixed here.
