### ISSUE TITLE
Aeon Labs multisensor, temperature reading issue

### ISSUE THREAD

**Issue by trusk89** [openhab/openhab#2454]
Response form Aeon Labs support,

Hi Alex,

The issue is caused by the wrong GET CC sent from the gateway/controller/OZW. The controller should be sending the Multilevel sensor GET CC to the Multisensor.

1. If request the temperature of Celcius:
Sending Multi level Sensor Get: 01 84 D0 9C 01 41 82 0E 05 31 04 01 00CB.

2. If request the temperature of Fahrenheit:
Sending Multi level Sensor Get: 01 84 D0 9C 01 41 83 0E 05 31 04 01 08C2

Cheers,
Chris

**Comment by cdjackson** [comment]
I'm seriously considering not fixing this (at least now).  It's not simple to add this, and I think it might break other devices.
What I also note is that in the new Gen5 version, Aeon have fixed their bug. I've not tried to send a request with the extra byte (might try that though) to see if it responds to that as well.

So, for now (ie the upcoming release) I won't change the way the binding works. What I propose instead is to disable polling of this channel which can be set in the database. In reality, I think polling of battery devices is a bit pointless (mostly - not completely) since they have to wake up before they can be polled, so you might as well just configure them to send the data without polling. Polling a battery device will also waste more power than sending unsolicited (since more packets get exchanged than a simple unsolicited send to an association group).

The problem with implementing this change is working out how to get the data into the CC since there's a separation between the OH item, and the CC.

**Comment by trusk89** [comment]
Can't it be done just for this multisensor?

**Comment by cdjackson** [comment]
No - that’s the problem. We’d need some way to determine that this was the sensor, or configuring it through the database which isn’t so easy.  I think it’s best to have the device send messages automatically anyway…

I’ll look at this again later, but it’s not as easy as I’d hoped, and I don’t want to break other devices when this is something easily worked around without thinking it through properly.

**Comment by trusk89** [comment]
Of course, and I agree that the best usage for sensors in general is letting them send status updates. But as long as the issue still reproduces in some way even when the controller is not polling, it would be nice to have, at least at a future time.

**Comment by cdjackson** [comment]
Fix implemented previously in database. As above, no code update will be made.
