### ISSUE TITLE
Split up openhab.cfg into seperate conf.d/<package-name>.cfg files

### ISSUE THREAD

**Issue by gersilex** [openhab/openhab#2597]
For upgrades and better management, config files should be split up into files, which...

- can be shipped with addons
- only affects the own settings

I suggest a new subdirectory "conf.d" where alle files can be placed.

The folder should be referenced or included in the main openhab.cfg with something like `include conf.d/*.cfg`.

**Comment by kaikreuzer** [comment]
FTR: This is already in place for openHAB 2, see https://github.com/openhab/openhab2/blob/master/docs/sources/installation/runtime.md#using-add-ons.

Don't know if @teichsta wants to do this for openHAB 1 as well, I'll leave that up to him.

**Comment by watou** [comment]
Will this change have the benefit of allowing per-bundle OSGi ConfigManager persistent data to remain undisturbed across restarts?  This would probably fall out of a switch to Karaf anyway, but I think it's important to change this from 1.x.

**Comment by teichsta** [comment]
> Don't know if @teichsta wants to do this for openHAB 1 as well, I'll leave that up to him.

If we'd find somebody volunteering to downport the OH2 solution i would be happy to add this to OH1.

> Will this change have the benefit of allowing per-bundle OSGi ConfigManager persistent data to remain undisturbed across restarts?

which kind of data do you think about?

**Comment by kaikreuzer** [comment]
> which kind of data do you think about?

He refers to the "clean" option, you might remember the longer discussion about that in another thread.

@watou, yes, the swtich to Karaf will address this - actually in Karaf your can also decide whether you want to always do a clean or not. I am still afraid to get difficult to reproduce bug reports if we dismiss this as you never know what kind of properties might have been set in ConfigurationAdmin...

**Comment by watou** [comment]
@kaikreuzer I believe that the only risk of stale properties in ConfigurationAdmin has to do with the way it is populated from openhab.cfg, potentially leaving stale properties removed from openhab.cfg in individual bundles' ConfigurationAdmin properties unless a full wipe is done at startup (as must happen in 1.x).  There is probably even an undiscovered bug in 1.x when openhab.cfg is edited while running, where removed keys remain in the ConfigurationAdmin properties.  

If the mechanism of getting properties to bundles can be re-thought so it plays nicely with OSGi, then there will be no risk of this disconnect cropping up.  Breaking up openhab.cfg into per-bundle config files probably takes us almost all the way to a solution.

I think it's important because we want OH2 bundles to co-exist benignly with non-OH2 bundles in the same OSGi container, so a full wipe at startup will not meet that goal.

**Comment by kaikreuzer** [comment]
Yes, agreed. So let's wait for the move to Karaf and then see what we might still have to improve on the openHAB side of the config mechanism.

**Comment by belovictor** [comment]
I guess this will not be done in 1.x.
