### ISSUE TITLE
HTTP Binding: the option to not give an error if the URL could not be reached

### ISSUE THREAD

**Issue by SierraNL** [openhab/openhab#2708]
I'm using the HTTP binding to scrape values from the webpage of my solar inverters.
I use the caching option to do this.

But solar inverters shutdown at night, so I'm getting a lot of errors in my logs.
I can change the loglevel of the HTTP binding, but I'm using the binding for several other items.

So I would like an option for the HTTP binding, per cached item, if it should throw an error when the url could not be reached.

**Comment by watou** [comment]
One approach might be to use [logback filters](http://logback.qos.ch/manual/filters.html), but I haven't seen examples of this under OpenHAB.  A more generic issue than this one might be to enable and document examples of how to use logback filters, so special-case logging could be possible for everything in OpenHAB.

**Comment by teichsta** [comment]
hmm … i would rather enhance the configuration of the polling interval. Since this outage is a known behaviour, it would be great to configure the polling interval accordingly. Using Cron-Expressions rather than a number would come to my mind for that.

But, it would be great if you would discuss this new feature the Google Group beforehand in order to have the whole community on board. Once you've found a (well accepted) solution, please update this Featurerequest here.

Thanks, Thomas E.-E.

**Comment by watou** [comment]
Better control over when URLs are polled is certainly a better solution than selectively suppressing log messages.

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
