### ISSUE TITLE
Z-Wave load neighbor list from XML

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab#2721]
Hi,

I have several Z-Wave devices and some of them don't work properly because they haven't found suitable neighbors and they can't reach the controller.

In particular, I have 2 battery-powered Fibaro motion sensors that are pretty close from a Z-Wave mains-powered Aeon Labs repeater, but they don't have this repeater as neighbor. 
They try to communicate with nodes that are further away, and the communication fails. 
The final result is that I have 2 Z-Waves nodes that are almost useless.

I am using the latest 1.7.0-RC OpenHab.

In issue #1524, neighbor list loading was discussed. I thought that was already implemented, so I tried to force the neighbor list by changing the XML manually, but it does not seem to work.

My questions are:

1- Can I load the neighbor list from XML?
2- In case the answer is no, what can I do for my devices to work? 
I've tried to heal the network several times with Habmin. I have restarted OpenHAB several times. Nothing seems to work...

**Comment by cdjackson** [comment]
It is not possible to set thw neighbours - tgis is done by the controller only.


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: sercasyr <notifications@github.com> </div><div>Date:12/06/2015  10:26  (GMT+00:00) </div><div>To: openhab/openhab <openhab@noreply.github.com> </div><div>Subject: [openhab] Z-Wave load neighbor list from XML (#2721) </div><div>
</div>Hi,

I have several Z-Wave devices and some of them don't work properly because they haven't found suitable neighbors and they can't reach the controller.

In particular, I have 2 battery-powered Fibaro motion sensors that are pretty close from a Z-Wave mains-powered Aeon Labs repeater, but they don't have this repeater as neighbor. 
They try to communicate with nodes that are further away, and the communication fails. 
The final result is that I have 2 Z-Waves nodes that are almost useless.

In issue #1524, neighbor list loading was discussed. I thought that was already implemented, so I tried to force the neighbor list by changing the XML manually, but it does not seem to work.

My questions are:

1- Can I load the neighbor list from XML?
2- In case the answer is no, what can I do for my devices to work? 
I've tried to heal the network several times with Habmin. I have restarted OpenHAB several times. Nothing seems to work...

**Comment by sercasyr** [comment]
Why is that?
What about issue #1524?

In any case, what should I do?
The sensors are unreachable, and they shouldn't because of the repeater. 
There must be a way to make them work...

**Comment by cdjackson** [comment]
> Why is that?

There is no API or anything available to load neighbours into the controller - it's that simple. ZWave is a closed system - the controller is designed to do everything.

> What about issue #1524?

This is completely different. This is talking about restoring the neighbours so that we can display them in the UI - but there's no way to load them back into the controller.

Your only option is to fill the gaps with mains devices. Battery devices don't route, so you need to add some repeaters, or mains powered switches in a position to fill the gaps.

There's no way that I know of to influence the routing - this is all done by the controller and the low level protocol layers.

**Comment by sercasyr** [comment]
Ok.

The thing is that the gap is more than filled with mains-powered devices. 

Between the sensors and the controller I have: 1 Aeon Labs Repeater (like 2 meters away from the sensors), 1 Aeon Labs Wall-plug Siren (it's just 1 meter away) and 1 Fibaro Wall Plug (like 5 meters away.

Of course, if I move the sensors closer to the controller, they work...

The controller is about 15 meters away from the sensors.
 It just makes no sense the route that I see in OpenHAB.

If you have some "trick" to make the device route the devices correctly or some configuration parameter that I can change, it will be very useful to me.
I have restarted the system like 20 times...

¿Do I have to set-up something in the repeater/mains-powered devices for them to repeat the signal? 

Thanks anyway, Chris.

**Comment by cdjackson** [comment]
I can understand your frustration - I would love to be able to provide some advice on how this really works (or doesnt work). However, as far as I know there's no way to influence this.

Also, the neighbours list is not the same as the routes (as far as I know). Neighbours are just that - devices that the other device has heard - it doesn't necessarily mean that a route exists or is used. There's no way to get the actual routes out of the system :( (again, that I know of at least).

Is the neighbour list updating? I know this is also something that doesn't work well (for unknown reasons). Often this command times out, although again, the controller should (!!) know everything and be able to control the system...

Like you, I have doubts that this works as well as I think it should but the closed nature of zwave makes it difficult to find much out. I'm currently working with some zigbee stuff (and have written a binding for OH2) and there's more information available there - I wish ZWave would open up, but I don't see that happening any time soon.

Likewise, I don't think there's anything you can set in the mains devices either - I know - I'm not being very helpful, sorry. I see similar posts pop up in the OZW forum, so if there's a way to do this stuff, it's not known unless you spend the money to get the information from the zwave people :(

**Comment by sercasyr** [comment]
Thanks for your help Chris.

I have managed to make them work (at least for the last 3 hours) but I wouldn't declare victory yet because I have the feeling that sooner or later is going to fail...

This is what I done:

1- I have enabled SUC mode in Openhab.cfg.

2- I have enabled masterController mode in Openhab.cfg.

3- I have moved one of the mains-powered devices further away (yes, further away, not closer ¿?).

4- I have woken up the sensors (triple click on the button) in a location very close to the controller and then moved them quickly to their final destination while they were awake (I did it several times).

5- I have added my repeater to Association Group 1 (device status) of my sensors. I know the repeater is not going to do anything with the data (other than physically repeat it) and that it shouldn't be in the association group, but maybe this action has some kind of influence in the routing process.

I think actions 1 and 2 have no impact. Maybe action 3 has some influence. 
However, I have the feeling that actions 4 or 5 made the difference.

As you said, it is impossible to know, but I just reported what I did in case it helps.

Maybe it just a matter of waiting a couple of days and I didn't influence the routing at all...

What I know is that "healing" does not work for me.
Indeed, the healing process caused one sensor that used to work to stop working!!!!
It also seems that restarting Openhab does make little difference.

Does anything I did make any sense??
I hope, at least, that we can bring some light to this issue. 
The binding is great. If the routing process were under control (or at least, understood), it would be awesome!!

**Comment by cdjackson** [comment]
> I have managed to make them work (at least for the last 3 hours) but I wouldn't declare victory yet because I have the feeling that sooner or later is going to fail…
> 
Great - it’s a start at least :)


> However, I have the feeling that actions 4 or 5 made the difference.
> 
For the configuration to be set in the first place (in battery devices) the device does need o be in direct contact with the controller. This is because a wakeup won’t be routed until it’s configured ‘properly’ by the controller. So, this might have been an issue if you’ve never done that

I’d be surprised if 5 makes any difference, but I wouldn’t rule it out.

Regarding 3… RF propogation is a strange thing - moving things around - even just twisting or rotating them, can make a significant difference due to antenna alignment. Also, moving it further away might be better if there are walls in the way - it’s not an exact science...


> As you said, it is impossible to know, but I just reported what I did in case it helps.
> 
> Maybe it just a matter of waiting a couple of days and I didn't influence the routing at all...
> 
> What I know is that "healing" does not work for me.
> 
Healing is a bad name - there is no ability really to do a heal in zwave but the heal process does a bunch of stuff that is normally useful - just no really healing...

> Indeed, the healing process caused one sensor that used to work to stop working!!!!
> 
What happened? Where did it stop?

> It also seems that restarting Openhab does make little difference.
> 
I wouldn’t expect it to make any difference.

> 
> The binding is great. If the routing process were under control (or at least, understood), it would be awesome!!
> 
As I said - I’d love to understand it better, but it’s a closed protocol and there are limited documents on how it all works under the hood. In theory, the controller should sort it all out, but like you, I have some doubts!  I’m always open to ideas, and always on the lookout for information, but what’s out there is limited :(

Chris

**Comment by sercasyr** [comment]
The sensors were added right next to the controller the first time. That wasn't the problem.
What I did differently this time is to wake them up near the controller and then move them away.
And... the association group thing.

Regarding the healing, I don't know what happened. One sensor that was working, stopped working right after the healing. 
I had to wake it up several times because it was gone (not marked as dead, but it didn't work).
And it's not the first time it happens. It also happened to me a couple of months ago when I was installing another sensor, so I am disabling the healing...

I think we can close the issue.
It's pretty clear that it's something the controller does...

**Comment by cdjackson** [comment]
Can we close this - you've opened another issue on the batter connection, and the original question about loading the neighbour list has been answered. If there's anything else that you think needs to be done for this issue, please can you restate it so I know what you're after.
Thanks
Chris
