### ISSUE TITLE
zwave binding(?) timezone

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab#2756]
Hi,

I noticed that in habmin, timestamps such as last packet received of a device are shown in UTC only
The tz offset is included, still it's a bit distracting if you don't happen to live in either Greenwich or somewhere along the way to North Pole ...
That's at least true for my zwave devices. All other time prints I have seen are fine,  so I believe this to be caused inside the zwave binding.

Chris, would you do us the favor to check and eventually change the output to evaluate the timezone that java runs under ?

thanks,
Markus

**Comment by cdjackson** [comment]
I'll take a look to see if this can be changed, but in reality, this time isn't meant to be read directly. In HABmin1 it is displayed as it comes from the binding, but in HABmin2, it gets reformatted into local time. The time information that comes out of the binding is just in a standard ISO format so that it can easily be interpreted by the UI without any confusion.

**Comment by cdjackson** [comment]
Just a comment on why I chose the ISO format... By using a standard format, we can be sure we understand the time when it is transferred between machines (in this case between the OH server, and the user interface) and there is no ambiguity when decoding it in the user interface. This is important if you want to do any processing on the time, which again is what is done in HABmin2. In the case you mention (last packet received) HABmin2 actually displays things like "Last packet was received 2 minutes ago", and if we don't use a standard format, you might find it says "1 hour and 2 minutes ago".

My personal feeling is it is best to stick with a standard format rather than have OH format it up differently for every user, and then have to try and decode this for display in the user interface...

**Comment by mstormi** [comment]
Am 18.06.2015 um 15:23 schrieb Chris Jackson:
>
> I'll take a look to see if this can be changed, but in reality, this 
> time isn't meant to be read directly. In HABmin1 it is displayed as it 
> comes from the binding, but in HABmin2, it gets reformatted into local 
> time. The time information that comes out of the binding is just in a 
> standard ISO format so that it can easily be interpreted by the UI 
> without any confusion.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openhab/openhab/issues/2756#issuecomment-113154303>.
>
Ok... yes I agree, it's better to keep the standardized output and have 
the GUI reformat it. If HABmin2 will do already, I'm fine.
(well, except that my Pi just crashed badly and now I'm struggling to 
reactivate most of my home, but hey, keep smiling .... ).

regards
Markus

**Comment by cdjackson** [comment]
Thanks - this shows how Habmin2 presents this...

![image](https://cloud.githubusercontent.com/assets/1041475/8235833/3e78291a-15dc-11e5-97c1-741b7d55e2e9.png)

Or in a slightly buggy mix of German and French (it should all be in German, but I just realised something is wrong with the time part of the translation!)
![image](https://cloud.githubusercontent.com/assets/1041475/8235884/952a2506-15dc-11e5-9185-f19c8f922b84.png)

**Comment by watou** [comment]
I've quite enjoyed the mixed languages in HABmin2 -- please leave that as an option! :smile:

**Comment by cdjackson** [comment]
Maybe it’s a good test for language students :)
