### ISSUE TITLE
Homematic: Support of ONTIME

### ISSUE THREAD

**Issue by wbuh** [openhab/openhab#2826]
Could you please insert a direct support of the ONTIME Parameter of a homematic actor, so that these device channels can be switched ON or OFF for a specific period that is controlled by the actor device itself?

**Comment by gerrieg** [comment]
That's supported, the Dimmer must be off and you have to set the ON_TIME value every time before you turn on the dimmer.

Example:
```
Dimmer my_dimmer 			{homematic="address=xxxx, channel=1, parameter=LEVEL"}
Number my_dimmer_on_time 	{homematic="address=xxxx, channel=1, parameter=ON_TIME"}

openhab send my_dimmer_on_time 5
openhab send my_dimmer 50
```
Turns the dimmer on with 50%, after 5 seconds it turns off

**Comment by csowada** [comment]
I would suggest to allow an addition parameter to my_dimmer instead of two items.
``Dimmer my_dimmer            {homematic="address=xxxx, channel=1, parameter=LEVEL, on_time=50"}``
or 
``Dimmer my_dimmer            {homematic="address=xxxx, channel=1, parameter=LEVEL, pre_parameter=LEVEL,50"}``

I think to work with two items or maybe a rule is not optimal for a real life problem.
