### ISSUE TITLE
ModbusRTUTransport missing one byte in receive stream

### ISSUE THREAD

**Issue by nickma82** [openhab/openhab#2843]
Carsten seems to [miss one byte](https://groups.google.com/d/msg/openhab/LDLtD2rJN1w/zy7G4ACokhsJ) while receiving a datastream from a _serial_ modbus RTU device. Which leads to an "[i.modbus.io.ModbusRTUTransport] - failed to read: CRC Error in received frame" [see](https://groups.google.com/d/msg/openhab/LDLtD2rJN1w/LtdJrNRSkkcJ).

He tried to debug the problem by sending/receiving the same datastream, that the Modbus-RTUTransport module would send/receive, with a test app. [With success](https://groups.google.com/d/msg/openhab/LDLtD2rJN1w/1kfbNZeKN5oJ).

He also "tried to run both openhab 1.7.0 and 1.8.0 snapshot, with both java 1.7 and 1.8.0" but [nothing changed](https://groups.google.com/d/msg/openhab/LDLtD2rJN1w/6cPKsiQ-G7EJ). He is running "openhab from a raspberry pi  2 with raspicomm".
##

**Comment by vicentini** [comment]
I have probably the same problem you're describing. I receive less bytes than expected for which reason the crc check fails. For me it seems that the connected device is somehow too slow to provide the requested message.

If I introduce a delay of 50ms between writeMessage and readResponse in net.wimpi.modbus.io.ModbusSerialTransaction.execute() I no longer encounter this problem.

Should there be an additional parameter here for slow devices (if this is really the reason for the problem)? Maybe @ssalonen could comment on this issue as he is currently working on the modbus binding?

Just for the record, I tested this with the following setup: PC (RS232) <=> Moxa TCC-80 (RS232-RS485 converter) <=> PLU-IO-4.5 (RS-485)

**Comment by ssalonen** [comment]
Please try out this version: https://github.com/openhab/openhab/pull/4226

The default timeout has been increased to 1.5s and there is a small delay between last request's read and next request's write (default 35ms).

**Comment by vicentini** [comment]
I thoroughly tested the setup with version #4226. It seems the problem doesn't lie only in modbus binding bundle.

@ssalonen In ModbusRTUTransport class I'd suggest to also set *m_CommPort.enableReceiveThreshold(1)* for reading the function code as it's done for everything else (uid, bc, data and crc). Otherwise it's possible the function code can't be read correctly, I believe.

The communication problem I stumbled upon has to do with this thredhold enablement. Somehow the code is not blocking and therefore not waiting for the bytes to be received, the *inputstream.read* method directly returns -1. Therefore I get the error *"Error reading response (EOF)"*.
As explained in my previous post, if I wait long enough between write request and read response, I receive the whole message correctly.

Testing with different serial ports I get an even stranger behavior. The non-blocking error only occurs when using usb-to-serial adapters (FTDI integrated in my gateway as well as a Prolific adapter used with my computer) but not with the native serial port on my computer's mainboard.

Has someone made similar experiences?
@nickma82 Did you also use such an adapter for serial communication, how is your setup?

**Comment by ssalonen** [comment]
Thanks for the response @vicentini! The receive threshold should keep it's value even if there are read() calls in between...

Since [L125](https://github.com/ssalonen/openhab/blob/modbus-pooling-pr/bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusRTUTransport.java#L125) the threshold. It should be still active when reading the FC at [L129](https://github.com/ssalonen/openhab/blob/modbus-pooling-pr/bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusRTUTransport.java#L129).

I can confirm that indeed the code was not properly blocking before, causing many issues. 

If I understood correctly you had issues also with version #4226 ? If yes, could provide TRACE level logs (net.wimpi.modbus and org.openhab.binding.modbus) and paste them to the #4226 or here?


Best,
Sami

**Comment by vicentini** [comment]
Ah, got it. I thought the threshold is decremented for every received byte.

I tested it with #4226, but not with the whole bundle. I actually just wrote a Test class opening a serial port and calling a modbus serial transaction with a simple modbus request in order to isolate the actual problem.

I'm gonna log the test case and see if it can help somehow.

**Comment by vicentini** [comment]
I tried it now with trace log level, unfortunately with no useful additional output.

> DEBUG [ModbusRTUTransport.java:77] Sent: 02 03 00 0a 00 01 a4 3b 
> TRACE [ModbusRTUTransport.java:127] Managed to read at least one byte
> ERROR [ModbusRTUTransport.java:171] Last request: 02 03 00 0a 00 01 a4 3b
> ERROR [ModbusRTUTransport.java:172] failed to read: Error reading response (EOF)
> ERROR [ModbusSerialTransaction.java:198] execute try 1/3 error: I/O exception - failed to read. Request: net.wimpi.modbus.msg.ReadMultipleRegistersRequest@37e67d34 (unit id 2 & transaction 1). Serial parameters: SerialParameters@b1320f9[portName=COM8,baudRate=9600,flowControlIn=none,flowControlOut=none,databits=8,stopbits=1,parity=even,encoding=rtu,echo=false,receiveTimeoutMillis=1500]
> ...

I instantly receive -1 for uid, therefore the EOF error.
Something's wrong with the used NR Java Serial library not waiting for the answer to arrive (even though set to wait for one byte). I'll head over there to further investigate the cause of this problem.

Thanks for your help Sami!

**Comment by ssalonen** [comment]
Can you please paste the full log in pastebin, with timestamps please

Best,
Sami
