### ISSUE TITLE
ZigBee Binding via CC2530 ZNP specification

### ISSUE THREAD

**Issue by YupiterOlympic** [openhab/openhab#2844]
Hi all!

I would like to contribute some functionality as ZigBee-binding. The functionality is based on CC2530 ZNP specification.

I tested it with CC2538EM dongle from Texas Instruments.

At this moment the list of supported clusters is:

Realized:
  Tested:
    - On/Off Cluster (0x0006)
    - Color Control Cluster (0x0300) + Level Control Cluster (0x0008)
    - Simple Metering Cluster (0x0702)
    - Temperature Measurement Cluster (0x0402)
    - Relative Humidity Measurement Cluster (0x0405)

  Not tested:
    - Fan Control Cluster (0x0202)
    - Illuminance Measurement Cluster (0x0400)
    - Temperature Measurement Cluster (0x0402)
    - Pressure Measurement Cluster (0x0403)
    - Flow Measurement Cluster (0x0404)
    - Illuminance Level Sensing Cluster (0x0401)
    - Occupancy Sensing Cluster (0x0406)
    - Thermostat Cluster (0x0201)
    - Dehumidification Control Cluster (0x0203)
    - Thermostat User Interface Configuration Cluster (0x0204)
 
In progress:
  Pump Configuration and Control Cluster (0x0200)

And just mandatory cluster attributes are supported.

**Comment by cdjackson** [comment]
Hi,
Just for information, there is a ZigBee binding being built for OpenHAB2 that you might be interested in contributing to? If I understand the roadmap for OH1, the next release will be the last, so you might be better to contribute to the OH2 binding?

Just a thought…

Chris

**Comment by mast** [comment]
@cdjackson Chris, do you know when this last release will happen? (I can't find roadmap for OH1). I think it'd be interesting to see it in OH1, considering that OH2 roadmap is unknown yet..

**Comment by cdjackson** [comment]
I believe the last OH1 release will be late this year - October or November time. At this time we would also expect the OH2 beta to be released followed early next year (may May based on the standard release plan) for the first OH2 release. 

At least that's my understanding. 

Chris

Sent from my iPhone

**Comment by kaikreuzer** [comment]
> At least that's my understanding. 
> 
Yep, At least that is the rough plan :-)

**Comment by YupiterOlympic** [comment]
Hi Kai, Chris,

I am trying to start the OH2 ZigBee-binding.

I red the 'instead of the global configuration/openhab.cfg file, there is now an individual file per add-on in conf/services'-note and created the ./conf/services/zigbee.cfg.

After that I wrote 'zigbee:port=/dev/ttyACM0' to the ./conf/services/zigbee.cfg and started the OH2 system (called ./start_debug.sh). In logs I saw the following:
[INFO ] [ZigBeeCoordinatorCC2530Handler:114  ] - Connecting to serial port []
[ERROR] [ZigBeeCoordinatorCC2530Handler:134  ] - Serial Error: Port  does not exist

I changed the string on 'port=/dev/ttyACM0' and had the same logs.

Could you please explain how can I configure the serial port for connection to my ZigBee stick?

Also it is not clearly for me - what is the difference between the *.items and the *.things?

Thanks.

**Comment by cdjackson** [comment]
Oh2 isn't configured through the CFESat or items files - it's all done through the UI. So you need to manually add the coordinator and enter the port into the box along with the pan id and channel.

Once you enter the coordinator and start discovery it will hopefully find your signee devices and add the new things and corresponding items. 

Sent from my iPhone

**Comment by YupiterOlympic** [comment]
Hi, Chris, Kai,

I use ZigBee-binding which was cloned from https://github.com/cdjackson/openhab2.git and was builded via Maven utility.

And there are some questions:

1) When I configure the ZigBee-stick I need to point PAN identifier and channel identifier. Are you sure that user - somebody like a driver or a builder - has an idea about these ZigBee parameters?

2) After that I need to point the device IEEE address. Why procedure of ZigBee network discovering has not been implemented - when devices, end points, clusters and cluster attributes are searched automatically, without additional data from user? As far as I know ZigBee technology allows it (at least I have implemented OH1 ZigBee-binding in this way for CC2538EM dongle from Texas Instruments).

Thanks.

**Comment by YupiterOlympic** [comment]
Hi Kai, Chris,

To Kai questions:

1) I have watched OpenHAB2 presentation video, I have started OpenHAB2 and in Paper UI I do not see 'Inbox' tab (please see attached PNG
![openhab2_device_list](https://cloud.githubusercontent.com/assets/9438293/9221944/b2e7cd6a-40f6-11e5-8f40-498d0df2394c.png)). What is may be wrong in UI? How should I configure it after downloading?

2) Could you please explain what is the purpose of the "ADD GROUP" clickable link.

3) What do the "INITIALIZING", "UNINITIALIZED", "OFFLINE" etc hints mean? For example, my ZigBee stick is already initialized and gets data from the ZigBee devices (as I can in the logs) but his state (INITIALIZING) points that the device is not whole initialized yet, the stick initialization is in progress yet. What kind of data do I need to send to Thing manager for INITIALIZED-state of my stick?

To Chris questions:

1) What the commit number of ZigBeeApi library do you use? I have found some algorithmic errors in this library on b8122b86017632caf966030e854e326223487303 commit (by the way, it is your commit). Code was clonned from https://github.com/cdjackson/openhab2.git

2) You do not implement whole announced functionality, am I right? I just see the handlers for stick and for dimmable light functionalities. The handlers for temperature and On/Off are absent.

Thanks

**Comment by cdjackson** [comment]
> I do not see 'Inbox' tab 

I can't see your PNG as work blocks this but in PaperUI Inbox is in the Thing Discovery menu. There is no explicit menu called inbox though - just the discovery... This is the same in HABmin.


> Could you please explain what is the purpose of the "ADD GROUP" clickable link.

It adds a group :)  Groups can then be added to things/items etc with ESH, and can be used for whatever the system, or UI defines.  Grouping of items etc is a standard OH1 function so maybe there's documentation in the OH1 wiki.


> 3) What do the "INITIALIZING", "UNINITIALIZED", "OFFLINE" etc hints mean? For example, my ZigBee stick is already initialized and gets data from the ZigBee devices

This is maybe a question I need to answer. The system doesn't really define what is set - it's done by the binding so I would need to have a look at how this gets set - it's possible that there's a bug here, but if so, it's in the binding.

> What the commit number of ZigBeeApi library do you use? 

This is a good question. At the moment Tommy seems to have stopped doing anything with the library so I've been using my locally compiled versions. I will look at up-revving the library since no-one else seems to be doing it now (I have full access to the Zigbee 4 java repo).

However, if you have a bug, then please feel free to fix it - if you create a PR into the zigbee4java library I'll take a look and will merge it and update the zigbee binding. The bug isn't something to do with timeouts is it? I suspect I may have introduced a bug as I'm having some issues with battery device timeouts last night - initially I thought it was related to a new occupancy sensor I have, but I think it's not that as it also occurs on my temp/humidity sensors which worked fine until recently :)

> You do not implement whole announced functionality, am I right?

What do you mean? The library implements the announcement - both announcements and LQI based joining is implemented. However, in the binding, it receives these announcements, and then tries to do a zigbee type to ESH thing type link, and this is where we currently only have a limited set of devices supported.

> I just see the handlers for stick and for dimmable light functionalities. The handlers for temperature and On/Off are absent.

Correct - I am about to add temperature/humidity and occupancy sensors in the coming few days. I have been working on how best to link what the library calls devices, and what ESH calls things - for instance, I have an occupancy sensor which has 6 or 7 zigbee endpoints, and this needs to be mapped into an ESH thing and a thingHandler. Hopefully this will be done in the next few days though as I need it for another user...

Chris

**Comment by kaikreuzer** [comment]
>  1) in Paper UI I do not see 'Inbox' tab

This is now under "Setup Wizard"

> 2) Could you please explain what is the purpose of the "ADD GROUP" clickable link.

It is creating a Group Item with "home-group" tag, so that it appears as a tab in the Control part.

> 3) What do the "INITIALIZING", "UNINITIALIZED", "OFFLINE" etc hints mean?

See https://www.eclipse.org/smarthome/documentation/concepts/things.html#thing-status

**Comment by YupiterOlympic** [comment]
Hi Chris,

Yuo wrote: "if you have a bug, then please feel free to fix it" - I just want to attract your attention to some places in the code.

1) https://github.com/tlaukkan/zigbee4java/blob/master/zigbee-api/src/main/java/org/bubblecloud/zigbee/network/port/ZigBeeNetworkManagerImpl.java
    a) function checkZigBeeNetworkConfiguration() - Why this function? Why do we need pan Id and channel Id validation?
    b) line 250 - I think ZB_WRITE_CONFIGURATION command with ZCD_NV_ZDO_DIRECT_CB option which set to 1 is better instead of ZDO_MSG_CB_REGISTER command for all ZNP clusters (commands). When we get ZDO_MSG_CB_INCOMING response we need to process the 2 parse operations: to parse this message for the payload extracting and to parse the payload for the data extracting. And in ZCD_NV_ZDO_DIRECT_CB case we need to process just 1 parse operation - to parse received response for the data extracting. 
    c) line 351 - This dongle reset sets configurations to its default values. Is this reset really needed here?

2) https://github.com/tlaukkan/zigbee4java/blob/master/zigbee-api/src/main/java/org/bubblecloud/zigbee/network/packet/zdo/ZDO_STARTUP_FROM_APP.java
    a) line 50 - As I can see in CC2530 ZNP Interface specification this command has another parameter - it is start delay before the device starts in milliseconds. The parameter length is 2 bytes. By the way I have an error in this command description (in my version of document) - the length of command equals to 1 but really it equals to 2

3) https://github.com/cdjackson/openhab2/blob/zigbee/addons/binding/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/handler/ZigBeeCoordinatorHandler.java
    a) lines 86, 87 - I have casting exceptions here
    b) I got the following stack trace:
Exception in thread "Thread-23" java.lang.NullPointerException
        at org.bubblecloud.zigbee.network.discovery.ZigBeeDiscoveryManager.isInitialNetworkBrowsingComplete(ZigBeeDiscoveryManager.java:133)
        at org.bubblecloud.zigbee.ZigBeeApi.isInitialBrowsingComplete(ZigBeeApi.java:260)
        at org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler$3.run(ZigBeeCoordinatorHandler.java:218)
     This happens because the 'endpointBuilder' variable is not initialized. This  variable is initialized in https://github.com/tlaukkan/zigbee4java/blob/master/zigbee-api/src/main/java/org/bubblecloud/zigbee/network/discovery/ZigBeeDiscoveryManager.java in startup() method. So for avoiding this exception in https://github.com/cdjackson/openhab2/blob/zigbee/addons/binding/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/handler/ZigBeeCoordinatorHandler.java in initialiseZigBee() method the zigbeeApi.initializeHardware() invocation should be replaced by zigbeeApi.startup()

**Comment by cdjackson** [comment]
> 
> a) function checkZigBeeNetworkConfiguration() - Why this function? Why do we need pan Id and channel Id validation?
> 
I’m not sure, but this was always in the library - it’s not something that I’ve specifically added.


The code that you mention in all these ZigbeeNetworkManager have not been changed by me - I thought that you said that these bugs were introduced in one of my commits, but this code has always been in the library (probably from the OSGI version, but I’ve not checked).  That doesn’t make it correct of course, but just pointing this out...


> c) line 351 - This dongle reset sets configurations to its default values. Is this reset really needed here?
> 
The way I read the documentation - it doesn’t set the configuration to default. The documentation states that  this is the recommended startup for the ZNP (please check section 2.1.4.1 of the TI ZNP docs which describes the recommended startup) as follows -:
The recommended power-up procedure is as follows:

Application processor and ZNP power up.

The application processor initializes its UART interface.

The application processor sends a SYS_RESET_REQ to the ZNP.

The application processor receives the SYS_RESET_IND message from the ZNP. 


Do you read this differently or have I missed something?

> 2) https://github.com/tlaukkan/zigbee4java/blob/master/zigbee-api/src/main/java/org/bubblecloud/zigbee/network/packet/zdo/ZDO_STARTUP_FROM_APP.java <https://github.com/tlaukkan/zigbee4java/blob/master/zigbee-api/src/main/java/org/bubblecloud/zigbee/network/packet/zdo/ZDO_STARTUP_FROM_APP.java>
> a) line 50 - As I can see in CC2530 ZNP Interface specification this command has another parameter - it is start delay before the device starts in milliseconds. The parameter length is 2 bytes. By the way I have an error in this command description (in my version of document) - the length of command equals to 1 but really it equals to 2
> 
I would need to verify this, but it does look like you are right. This code has not been changed for a long time I think - again, probably from the original OSGI version of the stack, and it seems to work.

> 3) https://github.com/cdjackson/openhab2/blob/zigbee/addons/binding/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/handler/ZigBeeCoordinatorHandler.java <https://github.com/cdjackson/openhab2/blob/zigbee/addons/binding/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/handler/ZigBeeCoordinatorHandler.java>
> a) lines 86, 87 - I have casting exceptions here
> 
How have you saved these parameters? If they are not saved in the correct type, then you will get casting errors - this is (in my mind) a problem with the way ESH handles these parameters, but I know that it will not be changed. 


> b) I got the following stack trace:
> Exception in thread "Thread-23" java.lang.NullPointerException
> at org.bubblecloud.zigbee.network.discovery.ZigBeeDiscoveryManager.isInitialNetworkBrowsingComplete(ZigBeeDiscoveryManager.java:133)
> at org.bubblecloud.zigbee.ZigBeeApi.isInitialBrowsingComplete(ZigBeeApi.java:260)
> at org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler$3.run(ZigBeeCoordinatorHandler.java:218)
> This happens because the 'endpointBuilder' variable is not initialized. This variable is initialized in https://github.com/tlaukkan/zigbee4java/blob/master/zigbee-api/src/main/java/org/bubblecloud/zigbee/network/discovery/ZigBeeDiscoveryManager.java <https://github.com/tlaukkan/zigbee4java/blob/master/zigbee-api/src/main/java/org/bubblecloud/zigbee/network/discovery/ZigBeeDiscoveryManager.java> in startup() method. So for avoiding this exception in https://github.com/cdjackson/openhab2/blob/zigbee/addons/binding/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/handler/ZigBeeCoordinatorHandler.java <https://github.com/cdjackson/openhab2/blob/zigbee/addons/binding/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/handler/ZigBeeCoordinatorHandler.java> in initialiseZigBee() method the zigbeeApi.initializeHardware() invocation should be replaced by zigbeeApi.startup()
> 

I will take a look, but the purpose here is to break the startup and the hardware initialisation to allow a dongle to be reset to defaults, which is needed if the user changes the PanID or channel. Otherwise there is no way to set these parameters.


As I suggested earlier, I would strongly recommend that you create a PR or something rather than email lists of things that you think might be an error. It’s really difficult to review this sort of email, and it’s very prone to error! If you think the above should be changed, then please submit a PR through into the appropriate project - for the zigbee binding, please submit against my OH2 zigbee repository, and for change requests to the library, please submit against the library repository.

Thanks
Chris

**Comment by AlexeyIvantsov** [comment]
Hi Chris,

Please take a look at https://github.com/cdjackson/openhab2/pull/2

Thanks

**Comment by hmerk** [comment]
closed as this discussion is moving over to a openHAB2 implementation.
