### ISSUE TITLE
snmp: dont use port 162

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2877]
The snmp binding should be configurable in the meaning of "I need a local snmp server"or "I just want to get snmp values from other server".
I don't need running a ocal process on port 162, but I want to read snmp values from other server.
As my openhab is not privileged to run a port below 1024 and I don't need to run the trap-forwarder (snmptrapd), I would like to ask for configurable parameter, which switches the usage of port 162 on or off.

Without enough privileges and without the trap-forwarer the binding doesn't start and is not useable.

Would be nice, if this enhancement could be implemented. Thanks in advance for your great work!
##

**Comment by cdjackson** [comment]
Why cant you just change the port number to 1024? (or maybe I misunderstand?)

**Comment by Alpoy** [comment]
Openhab.cfg defines the snmp:port and snmp:community configuration as OPTIONAL. So it shouldn't be dependent on snmpd to run SNMP GETs (client requests).

Have you tried to run the binding with "snmp:port" and "snmp:community" commented out (as in not defined) in openhab.cfg?

**Comment by cdjackson** [comment]
> Openhab.cfg defines the snmp:port and snmp:community configuration as OPTIONAL. So it shouldn't be dependent on snmpd to run SNMP GETs (client requests).
> 
I'm not sure I understand - if it’s optional, you can still use it. This is how the wiki is written too I think?

> Have you tried to run the binding with "snmp:port" and "snmp:community" commented out (as in not defined) in openhab.cfg?
> 
I'm not sure - I have snmp:port=162 in my config. 

If your point is that you must have something in the cfg file, then this might be the case. Quite a few bindings won’t actually active unless there is some configuration - I forget if this is the case with snmp or not as I set this up a few years ago, so I’m not sure I’ve every tried no configuration at all.

**Comment by Alpoy** [comment]
As I understand he only wants to run _polls_, but he can't because the binding demands a port to bind to that's below 1024 (default 162, but it requires root privileges). Now since the binding defines the PORT and COMMUNITY as optional I can only assume that's because you don't have to run the binding with SNMPD enabled (which make sense).

So I wonder if he has tried to run the binding without the port/community setting, and there is "some" configuration needed he could add a couple of default values in openhab.cfg like:
snmp:timeout=1500
snmp:retries=1

**Comment by cdjackson** [comment]
> So I wonder if he has tried to run the binding without the port/community setting

That was my original point. You should be able to set the port by using the :port config, and this should allow you to run with any port number you want (ie above 1024).

**Comment by Alpoy** [comment]
Hm yeah if the binding *demands* a listening port that is the simple solution to the problem clearly. I thought you could opt out on the listening service (traps) by not defining the port, but I misread the wiki.

Then I kind of agree with staehler, a feature request on the binding would be to enable/disable traps (listening) to avoid the "problem".

**Comment by J-N-K** [comment]
One SHOULD be able to opt out completely. There is no reason to keep a port open if the service is not used. From the security point of view one should try to open only the ports that are needed.

**Comment by staehler** [comment]
Well, yesterday I tried to run snmp-binding with default options in openhab.cfg, which means port:162. The binding didn't come up, which lead me to my feature request.
I don't want to run open ports, if they aren't used. That's why this serverside smtp should be optional.
@cdjackson : I think it would work, to run smtpd on an unprivileged port (>1024), but this would be a workaround, weakening the security.

**Comment by cdjackson** [comment]
Clearly the binding MUST have a listening port - otherwise it can't receive the incoming PDU. This is required for whatever mode you use (ie even for GET type requests). As far as I remember (which is badly! :) ) the binding only opens a single port - it uses this to transmit the GET requests, and to receive the responses, and also to receive the TRAPs.

The ```port``` config setting allows you to change the port, but either way, a port needs to be opened. 

It's been a while since I looked at the binding (ie about 2 years!), but why is snmpd needed? Isn't snmpd a daemon used to process requests from a snmp management software, and then to respond with the requested data?  The binding is doing the requesting - it's not using snmpd (is it?). Or are you wanting to run snmpd on the same computer as openhab is running on and have the binding request data from it? If so, this is independent of the binding (or maybe I just don't understand :) ).

> Well, yesterday I tried to run snmp-binding with default options in openhab.cfg, which means port:162. The binding didn't come up, which lead me to my feature request.

I think I said above, but many bindings need to have some sort of configuration in the cfg file in order for the 'updated' method to be called, which is what allows the binding to start up. I just had a quick look, and it looks like this is the case for the snmp binding - there needs to be something configured in the cfg file.

**Comment by Alpoy** [comment]
Hm, the binding doesn't need a listening port if it's not suppose to receive traps or answer remote GET requests.
If it's only gonna poll other nodes/servers/routers the "incoming PDU" port would always be the session source port (random). Just like HTTP sessions and any other service AFAIK. 

Ref:
https://en.wikipedia.org/wiki/Simple_Network_Management_Protocol#Protocol_details
https://en.wikipedia.org/wiki/User_Datagram_Protocol#Packet_structure

**Comment by cdjackson** [comment]
The port (whatever it is - session or whatever you want to call it) is still listening for incoming data, but it's not accepting incoming connection requests, but it's the same thing as we're using UDP which is a connectionless protocol!

In this case, the snmp server isn't using what you are calling a session port - the port that it uses is defined in the cfg file rather than being randomly generated, but that's the only difference. You may be able to make it random by setting it to 0 - I've not tried this but it's not an uncommon way to set a variable port when opening an IP port. In this case, we use the snmp4j library rather than direct socket IO so I don't know what this library does (their javadoc doesn't say either from what I could see with a quick look).

**Comment by J-N-K** [comment]
I did have a quick look at the code. It should be quite easy to switch off the "server" functionality by not opening a port in SnmpBinding.listen(). The question is how the user should indicate that this is the requested behaviour, because the current implementation uses 162 as default if no port is configured. Maybe setting the port to 0 disables opening a port? This is fully backward compatible and 0 isn't a valid port anyway.

**Comment by J-N-K** [comment]
After digging deeper in the code SNMP4J does not support opening a listening port only when it is awaiting an answer to a request. So as long as SNMP4J is used in this binding, the FR cannot be fulfilled. I would vote for closing with "Wont-Fix". 

It should be considered if a random port is used instead of 162 as default.

**Comment by 9037568** [comment]
Per the analysis by @J-N-K, unable to fix with the current library.
