### ISSUE TITLE
Mios binding does not support RGBController1 service

### ISSUE THREAD

**Issue by beowulfe** [openhab/openhab#3078]
There is no alias for urn:upnp-org:serviceId:RGBController1, which means you can't use RGB color bulbs in OpenHAB.

**Comment by mrguessed** [comment]
To be clear, you can use any serviceId without it being present in the service aliases file.  That's simply a convenience for using short names in the config files.

More than happy to see aliases added for all commonly used serviceIds, since it's a PITA to work with the fully qualified names, but it's really just a convenience.

**Comment by beowulfe** [comment]
Closing this per the discussion on PR #3079
