### ISSUE TITLE
ebus binding 1.8-SNAPSHOOT Wolf CSZ-1 Solar-Values

### ISSUE THREAD

**Issue by Truxen** [openhab/openhab#3084]
After updating to the current Snapshoot-Build the values of my Solar-Panel won't be parsed.
I have made a downgrade of the ebus-binding. Now it's working fine again.

**Comment by Truxen** [comment]
Is there any need for additional information to solve this issue?

**Comment by csowada** [comment]
Oh, an issue.
Have you checked the new ids? They've changed to have more structure...
https://github.com/csowada/openhab/blob/ebus-update-pr1/bundles/binding/org.openhab.binding.ebus/docs/json-configs.md

**Comment by csowada** [comment]
I currently working on an update for this pull request. It should help vaillant users to combine different commands to one item.

But do you had any success with the new ids?

**Comment by Truxen** [comment]
No i did't try the new ids. As you have created them for the CSZ-2: where can i find the documentation for the message of my CSZ-1?
Did you reverse-enginiered them? And if so: how?

**Comment by csowada** [comment]
Sorry, there are no documentation for csz-1, but I think configs from csz-2 should work. But there is no documentation about the protocol. So I reverse-enginiered the protocol by myself. But most telegrams are simple, one value of type "word" multiplied with 0.1 etc. Than I compared it with values from my heating controller display. Now it's easier because I bought the interface ISM7i to capture new commands.
 
But in terms of your solar module, you should use id's from configuration file https://github.com/csowada/openhab/blob/ebus-update-pr1/bundles/binding/org.openhab.binding.ebus/docs/json-files/wolf-sm1.md and add "ebus:parsers=...,wolf-sm1" to openhab.cfg.

BTW: You should wait until this evening, I'll release a new version with new configuration syntax.

But we should close this issue, because it's a problem with an unreleased version. You can join us at the community forum: https://community.openhab.org/t/ebus-binding/3399

**Comment by steve-bate** [comment]
Closing issue based on comment from @csowada .
