### ISSUE TITLE
Weather Binding Caching mechanism

### ISSUE THREAD

**Issue by jowi24** [openhab/openhab#3092]
The weather binding seems to apply some sort of internal caching, i.e., a bound item is only updated, if the value actually did change. 

In my opinion, the caching can lead to problems, e.g.,

- an openhab rule cannot distinguish between "item changed" or "item was updated", because the item is only updated when it actually changed
- it is impossible to detect if the current value of an item is "fresh", i.e. a maximum of <refresh interval> minutes old, or it is "old", e.g., because of network connectivity problems

I am sure, there must have been a reason to apply caching. However i do not realize. Can someone give me a hint? If not, I suggest to remove the caching to avoid the problems above.

**Comment by watou** [comment]
Maintaining state in the binding is generally disfavoured, and probably for the reasons you describe.  I looked at the code and see the use of [itemCache](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/bus/WeatherPublisher.java#L45) as you suspect.  I don't know the code well enough to understand why the caching is there, but there may be compelling reasons.

**Comment by teichsta** [comment]
@gerrieg could you help out and explain in more detail?

**Comment by gerrieg** [comment]
The cache is used for two things:
1.) If the item file is modified, the value can be published immediately from the binding. Each provider has limits on the free API, so i don't need to fetch the data for each change in the items and maybe exceed the daily limit.

2.) Isn't it unnecessary to flood the bus with the same values? You have a property condition.lastUpdate which contains the datetime of the last update of all values from the provider

**Comment by teichsta** [comment]
thanks for this update @gerrieg!

If i got you correctly you strongly recommend to keep up with the caching of the binding. I'll close #3116 for the reasons given above.

Thanks guys!

**Comment by LiamHD** [comment]
If you plot e.g. the temperature you get "holes" in your graph because of this caching.
Regarding
1) This is just a optimization for the time when you change your items file. But in the "productive use" this file does not change that often. And you could also restore old values from a perisistence if you need this feature.
2) I don't think you "flood" the bus. If you repot a new value let's say every minute. We are talking here about software for the "internet of things" / "smart home". It is designed to handle such use-cases. This is the task the bus is made for.

So I don't understand why this pull request is rejected that fast.

**Comment by teichsta** [comment]
Arguments you didn't bring up before. @gerrieg could you please comment?

**Comment by watou** [comment]
I would agree with @gerrieg 's point #1 to use the API sparingly in cases where unnecessary refetches might occur, but not with #2 because updates of the same value on a polling cycle are normal and don't overwhelm the event bus (excepting pathological situations that would be due to some bug).  One normal "problem" I've seen is the default events.log configuration, which grows too fast for normal users. But that's a config issue I think.

**Comment by spacemanspiff2007** [comment]
I have a rule which dynamically builds the Weather-String on update and I was wondering why it wasn't called. But now it seems quite clear.
Can you at least post an update every time you make an API-Request?

For me it is okay to wait two hours until the weather-data is shown correctly.
I'd use persistence if I wanted it to show the last entry.
My recommendation would be to update the items after the API-call is finished.
Until then, they're uninitialized.

Just for me for deeper understanding:
Does the timer for the API fetches run from binding startup or from the time the first weather-item is created?

**Comment by jowi24** [comment]
@spacemanspiff2007 My pull request actually fixes this issue, i.e., an update is posted every time an API-request is run.

I agree to @spacemanspiff2007 and @LiamHD that editing items is a rare case compared to the "productive use" time. So one should not optimize such cases with the drawback of added code complexity.

**Comment by LiamHD** [comment]
Regarding the code complexity: Do you know the saying: "There are only two hard things in Computer Science: cache invalidation and naming things." (http://martinfowler.com/bliki/TwoHardThings.html)

**Comment by gerrieg** [comment]
I looked at the code today, because it's been a while i wrote this and i am sorry to say, that #1 was a wrong information. I had this cache during development, because i reached the limits to often while testing.
So forget #1, sorry!!

For #2 as @LiamHD says, plotting will have holes if the item is not updated with the same value. 
@teichsta 
What is the 'official' statement from the openHab team in such situations? 
If regularly updating items with the same values is OK, you can accept the PR from @jowi24

**Comment by teichsta** [comment]
@gerrieg the 'official' statement is "it depends" ;-)

We discussed caching (and thus updating items) several times depending on the specific bindings. Overall we merely came to the conclusion that sending updates when they occur (even if the value didn't change) is the better solution.

Since in this case there are drawbacks (holes in graphs) it's probably better to remove this updateOnChangeOnly behaviour.
