### ISSUE TITLE
Better guide for beginners working with Raspberry Pi

### ISSUE THREAD

**Issue by jamesabruce** [openhab/openhab#3141]
After struggling to get things working from the generic instructions here, I decided to write a simpler guide  to getting OpenHAB installed on the Pi, and also explain some of the basic concepts of OpenHAB:

http://www.makeuseof.com/tag/getting-started-openhab-home-automation-raspberry-pi/

Is there any chance we could get this linked to from the official wiki? I didn't want to edit the page without permission.

**Comment by watou** [comment]
Your guide is truly great and helpful, bit I did notice that it diverges slightly from the existing wiki pages for installing on Linux.  There is/was an Instructables guide that became fairly out of date and began to actually complicate people's installs instead of help. Do you have thoughts about approaches to prevent unhelpful divergences from devolving in the case of your currently excellent guide?  

Many thanks for your contribution (from one user to another)!

**Comment by jamesabruce** [comment]
I don't think that's solvable, really. The wiki instructions for installing on linux, when used with the Pi, simply don't work - and it's putting off lots of beginners like myself. I think as long as it's specified exactly which versions the guide is for, there shouldn't be an issue: once something is out of date, it can just be delinked and something updated written.

**Comment by watou** [comment]
I had a different experience with the wiki instructions, but your idea to give very specific context to your guide (versions, models, etc.) makes sense, so no one can be led astray as time creates discrepancies between the "source"  instructions and your guide.  Do you have critiques or suggested edits to the wiki pages that could alleviate problems for those who don't follow your guide?  

Thanks again for your awesome contributions.

**Comment by jamesabruce** [comment]
I'm not a linux expert, but the main issue for me was that when logged in as Pi user, the apt-get step requires using sudo, which installs the openHAB package as root, and then OpenHAB just doesn't work. It needs to be chowned as openhab user before OpenHAB will even start. 

The default JVM is also set to OpenJava, so you need to manually change that to the Oracle version (which is installed, but not used, in the current version of Raspian) before a secret key is generated for my.OpenHAB access. 

My other issue with the instructions is that it's not clear where the files get installed to, so I had to search around finding the right file paths to even drop in demo content.

**Comment by SierraNL** [comment]
Isn't it a bug in the package that it doesn't chown openhabs directories? Since it does create an openhab user to run the service (it does in Ubuntu at least) ?

**Comment by watou** [comment]
If there are issues with install on Raspbian (or installation documentation), please report them with new issues here! Perhaps @theoweiss might have thoughts on this? :)

**Comment by teichsta** [comment]
@theoweiss could you please have a look at this chown issue? Thanks, Thomas E.-E.

**Comment by kaikreuzer** [comment]
@jamesabruce, Your guide is indeed very nice and definitely helpful for many beginners.
I am wondering, why you ask if we can link to it from the official openHAB website/wiki - wouldn't it be a much much better solution to include it directly on the official website/wiki? It shouldn't be hard at all to get the content into markdown format. Having it on the official site would help with the "decay" problem - everbody would be able to update the content if something changes on the install procedure.
If you feel that the wiki isn't the nicest place, I would also offer to use your content on the page http://www.openhab.org/getting-started/, which anyhow definitely needs a refresh. What do you think?

**Comment by jamesabruce** [comment]
Hi Kai. First, thank you for developing such an awesome system - I'm so glad you took a moment to check out my guide. 

It's entirely self interest that I'd like a link – the site I write for won't authorize another follow up guide to be written unless it gets enough traffic. That said, I'd be honored to have some of the guide copied, but the site will only allow it if an attribution link accompanies it.

**Comment by kaikreuzer** [comment]
Hi James, glad you like openHAB and that you are appreciating the efforts that have gone into it.
Requiring "enough traffic" and "attribution" does not sound like a good place to put documentation. If I understand your answer correctly, you chose the site because you wrote the guide on their behalf (i.e. being paid by them) or because you get some revenue share from publishing it there?
Wouldn't it be a wonderful option to show your appreciation by contributing to the project through improving the content that is available on the wiki/website?

**Comment by jamesabruce** [comment]
I'm a full time writer for MakeUseOf.com, yes. I guess "enough traffic" was a blunt way of putting it, but the fact is that if the guide isn't popular, I just won't be allowed to write about OpenHAB again. Like I said, happy for it to copied into the wiki, if a link is included. Sorry if this offends, attribution is pretty standard in the publishing world – I'm not much of an open source coder so I don't know how things are usually done here ;) 

I hope you can see my contribution as "outreach", by bringing more users to OpenHAB that otherwise wouldn't be here, each of which can then contribute in their own way.

**Comment by kaikreuzer** [comment]
Ok, understood. Of course such "outreach" is also welcome as it spreads the word about openHAB and will help beginners.
Nonetheless, I am not sure if we should include/link it in the wiki; there are many such blog posts (e.g. on instructables etc.), which aren't referenced either. We could think about adding a "references" section somewhere; but I am not too keen on that as it again would have to be maintained and it will never really be clear, which blog is still up to date and which isn't.

I might have a better suggestion though: I think a link to your post would perfectly fit into the Wikipedia article of openHAB, possibly providing you some good traffic. Currently the article is not public and only in draft, see https://en.wikipedia.org/wiki/Draft:OpenHAB. The reason is that it has been deleted by the admins, since I wrote most of it and they consider this to be biased. To get it active (again), we therefore require independent authors on it as well; you as a professional writer seem to be a brillant fit :-) So if you think you can find an hour some when to slightly improve the Wikipedia article, you are more than welcome to include a link to MakeUseOf.com in the "External links" section.

**Comment by teichsta** [comment]
so if i got this all correctly there on "real" issue left which is the (potential) permission problem which @theoweiss hopefully have a look at. @jamesabruce if you don't mind i'll close this issue. It would be great if you could open another (focussed) issue for it … Thanks in advance, Thomas E.-E.

**Comment by theoweiss** [comment]
I will look at this the next days and give some feedback.

**Comment by SkynetHome** [comment]
WOW! If multiple writers is what openhab needs to get a Wiikipedia page up I am happy to contribute some time, no attribution necessary!  If what James has written is a good example of what the Wikipedia page should include I am quite sure I can read his work and then rewrite it in my own words to suit! Borrowing from and improving on others work is indeed sort of the nature of an "open source" project!! Always glad to help out where I can!

@kaikreuzer Love your response above!!

**Comment by maxibelino** [comment]
i've read 100% of @jamesabruce guide, i found this guide just ...excellent! great work! And, it could be extended to explain further interaction with other sensors (or adding 'home made' sensors with arduino, etc)
great work for OpenHAB team; i hope i can help in this great project ;)
thanks!
Maxi

**Comment by kaikreuzer** [comment]
@SkynetHome Yes, we definitely need writers to get on Wikipedia - thanks for volunteering!
Yes, what James wrote is excellent, but the tutorial format is not necessarily the right structure for Wikipedia. As a template for possible content and structure, you could check e.g. the entries for [Plex](https://en.wikipedia.org/wiki/Plex_(software)) or [Kodi](https://en.wikipedia.org/wiki/Kodi_(software)) (thought they are VERY long, I would not aim for so much detail on openHAB).

**Comment by kaikreuzer** [comment]
@SkynetHome (or anybody else) - Would you be willing to work on the Wikipedia page? Let me know when you found the time to do so and I will request to get the page published again!

**Comment by richbeales** [comment]
@kaikreuzer I'm happy to lend a few minutes to the wikipedia entry too if it helps

**Comment by kaikreuzer** [comment]
@rich Would be great!
@SkynetHome Any news from you here?

**Comment by SkynetHome** [comment]
Sorry Kai I got caught up with a mobile app development project. Will see
if I can put something together this weekend!

**Comment by SkynetHome** [comment]
@kaikreuzer Sorry for the delay. I put in some work on the Wikipedia page this morning. It still needs some work adding links and completing the interfaces section. I will make additional changes later this evening if I get a chance.

**Comment by kaikreuzer** [comment]
Cool, thanks! Better late than never :-)
