### ISSUE TITLE
CometVisu Runtime Exception

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab#3238]
I am running OpenHAB 1.7.0 with CometVisu using the CometVisu Addon in version 1.7.1. When I am clicking on a Switch in CometVisu it is properly sending the command to OpenHAB but CometVisu is not refreshing it. Looking at the HTTP Requests sent by CometVisu I can see that they timeout. The request looks like this `http://192.168.1.50/services/cv/r?s=8ed18bfe-f6f0-47c5-99c7-da550e91b7f6&a=Light_GF_Child_Main&a=Light_GF_Child_Main_Color&a=Light_GF_Child_Bed&a=Light_GF_Child_Lava&i=1443869085065`. When I remove the i parameter (which seems to be some kind of time) it works fine, with the i parameter it's just loading forever. I am using Firefox and I do not have persistence enabled for the items, is that maybe the problem?

**Comment by peuter** [comment]
The Timeout is absolutely normal after 60 seconds without any item changed the request is terminated and restarted. The problem is that there are no item state updates send to the CometVisu (and thus the read request runs into the timeout). Have ou changes something in your item files. Currently there is a bug in the CometVisu backend which stops the updates after that. I created a Pull Request with a fix for that problem about an hour ago: 
https://github.com/openhab/openhab/pull/3237

So currently you need to restart openhab to get it working again.

**Comment by Flole998** [comment]
It was the items bug. Problem solved.
