### ISSUE TITLE
Aeotec door sensor state does not change

### ISSUE THREAD

**Issue by paragparandkar** [openhab/openhab#3277]
using
Aeotec z stick gen 5, door sensor, openhab , habmin
door status always shows closed

curl http://localhost:80t/items/Door_Motion/state

always give
CLOSED

item file -
cat /usr/share/openhab/configurations/items/default.items
Contact Door_Motion "Window [%s]" (DollHouse) {zwave="2:command=SENSOR_BINARY,refesh_interval=1,respond_to_basic=true"}

openhab.cfg has following configuration for z wave binding
zwave:port=/dev/ttyACM0

habmin shows door sensor with green circle as node 2

configuration parameters for node are set as -
send sensory binary reports on open close events - on for close, off for open
send basic also similar

door status value always comes as closed , even when door is open

**Comment by cdjackson** [comment]
As suggested previously, this would be better discussed on the forum (community.openhab.org) rather than as a bug here as there will be a wider audience, and someone might be able to help with your configuration.  I don't believe there will be a bug, so it would be better to discuss on the forum to see where you're going wrong, and if we find there is a bug, then we can open an issue to get it resolved.

**Comment by cdjackson** [comment]
Since you now have also asked this on the forum, I'll close this here.
