### ISSUE TITLE
Bugs in sendMail action

### ISSUE THREAD

**Issue by Dan1001** [openhab/openhab#3338]
There are at least two bugs in the sendMail action

First, image attachments arrive as a file called "Attachment" without a suffix/extension, and hence can't be opened on many systems.

Second, urls with basic authentication aren't accepted (i.e. username:password@), and give the error log I've copied below. Obviously a problem when using sendMail with webcam images.

(Opening up a new issue because the old one was closed, and I'm not sure it's monitored; apologies if that's wrong and I'm just duplicating posts)

thank you!

Dan

18:02:29.826 ERROR o.o.action.mail.internal.Mail[:97]- Error adding attachment to email.
org.apache.commons.mail.EmailException: Invalid URL set:http://admin:MYPASSWORD@192.168.1.145:80/dms.jpg
at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:367)
at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:311)
at org.openhab.action.mail.internal.Mail.sendMail(Mail.java:93)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: http://admin:MYPASSWORD@192.168.1.145:80/dms.jpg
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
at java.net.URL.openStream(URL.java:1037)
at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:362)
at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:311)
at org.openhab.action.mail.internal.Mail.sendMail(Mail.java:93)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by watou** [comment]
I think this issue is internal to the Apache Commons Email library.  I looked through the [release notes](https://commons.apache.org/proper/commons-email/changes-report.html) and it's not mentioned as being fixed in any release since 1.2.  Maybe you could raise an issue [there](https://issues.apache.org/jira/browse/EMAIL-159?jql=project%20%3D%20EMAIL%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20ORDER%20BY%20key%20DESC)?  Otherwise, there may be workarounds to copy the image locally to /tmp first and use a `file://` URL for sending the email, a good discussion for https://community.openhab.org.

**Comment by 9037568** [comment]
It appears some browsers have removed or deprecated the ability to pass
credentials in this way:

http://serverfault.com/questions/371907/can-you-pass-user-pass-for-http-basic-authentication-in-url-parameters
     https://code.google.com/p/chromium/issues/detail?id=123150

**Comment by 9037568** [comment]
And from RFC3986:

   *Use of the format "user:password" in the userinfo field is
   deprecated.  Applications should not render as clear text any data
   after the first colon (":") character found within a userinfo
   subcomponent unless the data after the colon is the empty string
   (indicating no password).  Applications may choose to ignore or
   reject such data when it is received as part of a reference and
   should reject the storage of such data in unencrypted form.*

**Comment by Dan1001** [comment]
Thanks - yes, I've tried working around it by downloading a local copy and then running sendMail on that, but then I run into the other bug that renames the file to "Attachment" without an extension/suffix.

**Comment by Dan1001** [comment]
thank you!

**Comment by watou** [comment]
Could you try [this JAR](https://dl.dropboxusercontent.com/u/4286376/mail-action-attachments/org.openhab.action.mail-1.8.0-SNAPSHOT.jar)  and tell me if the file name comes through on the attachment now?  Also, there is a version of the sendMail action in this JAR that accepts a list of Strings instead of a single string `attachmentUrl`.  If you pass in a `List<String>` instead of a `String`, it will attempt to attach them all to the email.

Please let me know if this JAR is worth submitting a PR for.  Thank you!

**Comment by Dan1001** [comment]
Thanks, but unfortunately doesn't work - gives me:

ERROR o.o.action.mail.internal.Mail[:162]- Cannot send e-mail because of missing configuration settings. The current settings are: Host: 'null', port 'null', from 'null', useTLS: false, username: 'null', password 'null'

(and of course the openhab.cfg settings were working fine with the old JAR)

Dan

**Comment by watou** [comment]
I don't see how the code changes in #3349 could lead to this configuration issue.  Did you do a full openHAB server stop and restart when applying the new JAR?  What seems more likely is a lifecycle issue that somehow failed to call `MailActionService.updated(Dictionary config)` when the JAR is replaced.  I will do some testing, but could you do a full server stop/restart with the test JAR in place?

**Comment by watou** [comment]
I saw the same log message as you, but then I
```bash
sudo /etc/init.d/openhab stop
sudo /etc/init.d/openhab start
```
and the new mail action JAR performed as expected (mail came through, attachment was named properly).  Please let me know if you see this or something different, and thank you!

**Comment by watou** [comment]
I was also able to send multiple attachments with a single email, and the attachments were named correctly:
```
import java.util.List

rule "Test sending email"
when
  Item SomeItem changed
then
  val List<String> attachmentUrlList = newArrayList(
    "http://some.com/link/to/a/file.jpg?fred=foo&bar=baz",
    "http://example.com/fred/wilma/betty/hamburger.jpg")
  sendMail("your@email.com", "Testing", "This is the message", attachmentUrlList)
end
```

**Comment by Dan1001** [comment]
ah, thank you... restarting openHAB didn't work, but rebooting the system did. Now works perfectly!

**Comment by steve-bate** [comment]
@dan1001, can this issue be closed?

**Comment by watou** [comment]
This was a two-part issue.  The first (attachments named "Attachment") is fixed in 1.8.  

The second ("urls with basic authentication aren't accepted (i.e. username:password@)") is not fixable in openHAB, since openHAB uses Apache Commons Email which handles the URLs.  The workaround is to pull the attachment locally, and then use a file:// URL to attach to the email.

**Comment by steve-bate** [comment]
@teichsta. This is a little complicated because it's two issues in one entry. Should we label it as "wont-fix" (for the second part) and close the issue?

**Comment by Dan1001** [comment]
Steve, I'm not sure - the attachment now arrives but it sometimes seems to be corrupted. When I have more time I need to look at whether there's something wrong in my workaround (i.e. the rule that pulls the attachment locally) or some kind of remaining bug...

**Comment by 9037568** [comment]
As noted by @watou, the attachment issue is fixed and the authentication issue can't be fixed.
