### ISSUE TITLE
FHEM Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#342]
_From [petersau...@hotmail.de](https://code.google.com/u/104081366712696080169/) on June 14, 2013 09:45:56_

There should be a FHEM binding for monitoring and control fhem devices.
Devices should be handled in FHEM (hardware driver) and the device value should be get or set over the device name.

Additional infos FHEM Java-Schnittstelle: http://forum.fhem.de/index.php?t=msg&th=10867&start=0&rid=0 Das Google-Projekt: http://code.google.com/p/fhem-java-api/ The Open Transporter: http://www.theopentransporter.de/

_Original issue: http://code.google.com/p/openhab/issues/detail?id=342_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.

**Comment by Tscherno** [comment]
I really would be interested in such a binding.

**Comment by snickers2k** [comment]
please add such function.. i think this would be a better alternative to homegear

**Comment by Tscherno** [comment]
Anything we can do to make this reopened?

**Comment by teichsta** [comment]
@Tscherno we (especially @steve-bate) are currently working hard to keep this issue tracker free from feature wishes since most of the contributors are simply not aware of this tracker of do not actively (and frequently) search through the open issues.

However our great community.openhab.org the perfect place to discuss feature request, find other interested users and (hopefully) some contributors helping to create the binding/enhancement in the end.

So could you please create a thread in the forum and refer to it here?

Thanks, Thomas E.-E.
