### ISSUE TITLE
Plex binding updating bus without changes to status

### ISSUE THREAD

**Issue by batfasturd** [openhab/openhab#3431]
When the device status is anything other than stopped it posts the status to the bus even if it has not changed.

It would be nice to see this plugin behave like the network health plugin and have a cache for changes. 

Thanks you.

**Comment by idserda** [comment]
I'd be happy to add this. I will however query the ItemRegistry directly for the current state instead of keeping a local cache.

**Comment by watou** [comment]
It is much preferred for bindings to stay ignorant of the ItemRegistry, and to post updates to items' states as they are known, instead of suppressing updates based on current item state.  Various unintended consequences emerge when a binding is suppressing its own updates.  This subject has come up regarding various bindings, and in a lot of cases an item cache or accessing the ItemRegistry has led to other problems.  Usually, the basis for the complaint about updates to the same state has to do with some unwanted downstream bahaviour, such as the default configuration of events.log, or rules that trigger on `received update` instead of `changed`.  I strongly discourage that bindings are changed or written to be stateful for items, unless the idea survives heavy scrutiny.

**Comment by batfasturd** [comment]
Watou, so your idea is to leave it alone and let it update as often as it updates? If that is the case I guess the second happy medium would be to keep the existing behaviour as the default and allow for someone to decide if they want to be stateful or not.
I guess I assumed it would hurt performance while playing movies as my Plex binding logs to the event bus every 2.5 seconds.

I run my network health binding with a cache as it polls many devices every 10 seconds. So far I have yet to experience any issues other than reloading configs and having Openhab show no data until the cache expires or I manually trigger via OSGI.

**Comment by watou** [comment]
I wouldn't assume that update events every 2.5 seconds would lead to performance issues, but if they somehow do impact performance, one could argue that either something in the Plex binding is simply polling more often than necessary (I don't know), or some rule or other event listener is handling the updates inefficiently.  It is not an issue, to my mind (and I recall a conversion with @kaikreuzer about this where he concurred), that there are multiple sequential events for the same item and state.  For example, if someone wanted to know the very latest time that an item's state was known, but the binding suppressed the event, then the binding has been somewhat hobbled from providing this fact to the user.

I think that the default configuration of events.log is not good, especially on flash memory devices like the Raspberry Pi, because it is logging all events for no reason other than possibly a debugging purpose, in which case it ought to default to no logging unless you want to know about the events.  That's why I set mine to WARN level in logback.xml.

To your point about caching in the network health binding, you identify issues when using caching in the binding that you know how to workaround, but ideally a stateless binding would need no workarounds at all.  I would argue against adding an optional cache to the binding, because doing so would lead to complexity that should not be needed, if instead the unwanted side-effects were addressed (like I do with my events.log by setting the logging level to WARN).

**Comment by batfasturd** [comment]
Thank you for elaborating further. Since I am not running on a Pi and have a decent VM I shouldn't worry about it too much and just change my rules and/or event logging. I am just thankful that the 1.8 version of the binding works with Plex home!

**Comment by idserda** [comment]
Fine with me, we'll keep the binding as it is. Can we close this issue?

**Comment by batfasturd** [comment]
Yes, that is fine, Thanks everyone!
