### ISSUE TITLE
Improve group function calculation of percent values

### ISSUE THREAD

**Issue by TheNetStriker** [openhab/openhab#3466]
I've tried to group a couple of percent values using the AVG group function and I found out that this changes the type of the value. Instead o a percent value (0 to 100) the group returns a decimal value. (0.0 to 1.0)

The android app e.g. only handles only 0 to 100 values for sliders. Is this an issue in OpenHAB or should the Android app also handle 0.0 to 1.0 values when using sliders?

https://community.openhab.org/t/hue-group-dimmer-slider-always-set-to-zero/3909/6
##

**Comment by steve-bate** [comment]
If you don't get an answer here, you may want to task your question on the community forum.

**Comment by TheNetStriker** [comment]
I already asked the question in the forum, but I didn't get any answers yet: https://community.openhab.org/t/hue-group-dimmer-slider-always-set-to-zero/3909/6

**Comment by steve-bate** [comment]
I'm assuming you are grouping DimmerItems with a PercentType value. Let me know if that's not correct.

It's strange (to me, at least), but a PercentType (which is a DecimalType subtype) must have a value in the range 1-100. However, if the value is retrieved from a DimmerItem as a DecimalType, the PercentType 1-100 value is divided by 100. That's why you are seeing 0.0-1.0 values from the average.

@kaikreuzer @teichsta Can you give some insight why the DimmerItem getStateAs function was implemented this way?

**Comment by kaikreuzer** [comment]
> Can you give some insight why the DimmerItem getStateAs function was implemented this way?

Yes! The reason is that SwitchItem.getStateAs(DecimalType) returns 0 and 1 for OFF and ON.
A dimmer that is at 100% is ON and thus maps to the very same value.

**Comment by steve-bate** [comment]
As you said, the AVG group function will not do what you want in this case. One workaround is to create a rule to calculate the average and update the group-related dimmer item with the percentage. You could also just create an additional item and scale the existing group AVG value by 100 and update an additional group item. (Also posted in community forum.)

Although you haven't explicitly asked for a feature, I'm going to relabel this issue as a feature-request for handling PercentTypes better in the ArithmeticGroupFunctions.

**Comment by 9037568** [comment]
This is no longer possible for OH1, as no further releases of the platform are planned.
