### ISSUE TITLE
Error in Frame handling in WEB UI and Habdroid

### ISSUE THREAD

**Issue by tbail** [openhab/openhab#3517]
Hi There,

while building my weather area in openhab i tried to implemnet a Frame with some dynamic data in it. Bases on the WIKI the Frame has a label and optional an item.

I created an item
DateTime SensorVerandaObservation	"Letztes Update [%1$td.%1$tm.%1$tY %1$tH:%1$tM]" <IconClock> (gSensorVeranda)

and put it into an Frame in my Sitemap
Frame item=SensorVerandaObservation label="Wetterdaten von [%1$td.%1$tm.%1$tY %1$tH:%1$tM]" {
removed some Stuff
}

Got no Error, the Headline of the Frame is somwhat puzzled. I Ecpected something like this:
Wetterdaten von 06.12.2015 19:30
but i get
Wetterdaten von span style=""06.12.2015 19:30/span (removed the brackets)
checked it in HAbdroid an the span ist replaced by []

Question: Is this a bug or a feature? Openhab Version is 1.7.1

Thomas

![image](https://cloud.githubusercontent.com/assets/13729461/11763201/e1353d9a-a101-11e5-9026-8b88d2f5a442.png)

**Comment by steve-bate** [comment]
@tbail For some reason you expected/actual looks the same. Did you try to paste HTML into the Markdown window?

**Comment by tbail** [comment]
@steve-bate 

Thats right, I removed the brackets to make the problem clear

**Comment by AlanGreene** [comment]
I stumbled across the same behavior when trying to achieve something similar to https://github.com/openhab/openhab/issues/2235. The frame heading is displayed as in @tbail's screenshot:

    itemLabel <span style="">itemValue</span>

The wiki at https://github.com/openhab/openhab/wiki/Explanation-of-Sitemaps#element-frame mentions the "item" attribute but does not document its purpose or the expected behaviour. I'm not entirely sure what the expected output would be but I don't think it should be outputting escaped markup into the frame title.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
