### ISSUE TITLE
openHAB on raspberry starting problems

### ISSUE THREAD

**Issue by devUBi** [openhab/openhab#3582]
I have some problems starting my openHAB on a raspberry PI. System is starting without any exceptions/errors etc. but mostly after startup UI is updated only once and no more change after that. UI is no more responsive. F.e. changing a switch has no effect and normally after a few minutes UI is no more available and even no events are logged/processed any more, so a restart is required. Normally it takes me 15-20 times restarting the openHAB system to get it running properly. I tried several things, delaying the openHAB start on booting for example, but no real effect. Seems to be in the openHAB system itself and not depending on any environment. Removing the homematic binding normally helps to start openHAB properly, but this can't be the solution. I put that binding into debug but even on starting the system properly or if it fails -> same successfull log messages from that binding. So i tried to analyse the startup process of openHAB and attached you will find 4 logs. 2 successfull starts and 2 failed starts. What is conspicuous to me in that files is, that on the successful starts the rules are loaded very late in the startup process compared to the failed startups.
Any ideas how to workaround this annoying issue? 

[failed1.txt](https://github.com/openhab/openhab/files/69442/failed1.txt)
[failed2.txt](https://github.com/openhab/openhab/files/69441/failed2.txt)
[running1.txt](https://github.com/openhab/openhab/files/69444/running1.txt)
[running2.txt](https://github.com/openhab/openhab/files/69443/running2.txt)

**Comment by watou** [comment]
If you could post your experiences at https://community.openhab.org, more people could help diagnose the issue.  Over at the community site, please post this information as well as how you installed openHAB, how you start it, which model Raspberry Pi and OS version you're using, whether you use external or network disks, anything that might be unique to your setup.  Also consider installing the latest openHAB snapshot version from https://openhab.ci.cloudbees.com/job/openHAB/ .  Please close this issue here and carry on at the community site.
