### ISSUE TITLE
Convert GoogleTTS binding into general WebServiceTTS binding

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab#3643]
As the GoogleTTS doesn't seem to work anymore (see [here](https://community.openhab.org/t/googletts-responding-with-503-error-even-after-the-url-fix/3385)), I would propose to replace it with a general binding for calling an HTTP "webservice". This way it should be possible to use e.g. [VoiceRSS](http://www.voicerss.org).

If you agree that this makes sense I would check what has to be adjusted and create a PR.

**Comment by watou** [comment]
Would it be better to flesh this out in a discussion at https://community.openhab.org ?  I would be interested to see there the objectives, and advantages and disadvantages of different approaches.  Please close this and start a topic there if you agree.  Thanks.

**Comment by kaikreuzer** [comment]
My suggestion is to continue this discussion at https://github.com/eclipse/smarthome/issues/584 - with this, I anyhow plan to decouple the TTS audio stream generation from playing the stream, so that not all the bindings (like Sonos, Squeezebox etc.) have to implement the TTS support over and over again, but only have to be an "audio sink", so that text is spoken independently of which TTS engine had been used.
