### ISSUE TITLE
Add to Z-Wave Database

### ISSUE THREAD

**Issue by drewwaite** [openhab/openhab#3662]
It appears that I have found another one. It seems to be the AU versions!

Can you please add the Fibaro RGBW Controller to the database. The XML file is the same as fgrgbw.xml.

[ID:3000, Type:900]

If you can point in the direction of what to do I can probably add the information myself.

Thanks again.

Andrew

**Comment by cdjackson** [comment]
You need to update the products.xml file - open this file in the database folder (in the zwave binding) - search for the device - add an extra reference (should be obvious what to do as you’ll see the references there) - save, and generate a pull request on git so we can get it added to the binding…

If you don’t do this though, please say so so that we can update it (i.e. I’ll assume you’re going to create this PR unless you say otherwise).

Chris

**Comment by drewwaite** [comment]
Not sure I did this right... I think I have created a pull request but it seems to be wanting to change more than 1 file!

**Comment by cdjackson** [comment]
I assume this is working and can be close?

**Comment by drewwaite** [comment]
Yes.This issue can be closed.
