### ISSUE TITLE
forEach does not work properly with java 8

### ISSUE THREAD

**Issue by HolgerHees** [openhab/openhab#3771]
the following simple rule works properly with java 7

rule "Scene 1"
when
        Item Scene1 changed
then
        if( Scene1.state == ON )
        {
                Lights_FF.members.forEach(kreis|{
                        sendCommand(kreis, OFF)
                })
                postUpdate(Scene1, OFF)
        }
end

if I switch to java 8 I got the following error message

ERROR o.o.c.s.ScriptExecutionThread[:50]- Error during the execution of rule 'Scene 1': Could not invoke method: org.openhab.model.script.actions.BusEvent.sendCommand(org.openhab.core.items.Item,java.lang.String) on instance: null

if I switch back to java 7 everything works fine.

I tested it with openhab 1.7.1 and 1.8.0

**Comment by HolgerHees** [comment]
I wrote an additional comment to this closed ticket. #2586

**Comment by pinkkoff** [comment]
I think it is critical bug. 
I try workaround like this:
```
for (kreis : Lights_FF.members) {
sendCommand (kreis, OFF)
}
```
and tis work for me now... Thanks @dhermanns in #3293

**Comment by HolgerHees** [comment]
thanks a lot. this workaround works for me too.!

**Comment by teichsta** [comment]
sound like an issue with Xtext in combination with the JDK. Since we won't do any Xtext within in the 1.x stream i doubt we'll find a solution. Could you double-check with the 2.x stream if this issue still occurs since Xtext has been updated there.

I'll close this issue for now. Please feel free to reopen if this issue also occurs with 2.x.

**Comment by pinkkoff** [comment]
Hm. Now OH2 doesn't support many protocols, isn't it? Many users use openhab1 now, why bugs are not fixed on it?

**Comment by kaikreuzer** [comment]
> Now OH2 doesn't support many protocols, isn't it?

It is, see https://github.com/openhab/openhab-distro/blob/master/docs/sources/addons.md#compatible-1x-add-ons
The aim is that almost all openHAB 1 bindings work there as well.

> why bugs are not fixed on it?

Simply, because nobody does it. If you come up with a PR to fix it, I think there is a very good chance that @teichsta includes it in a future bug fix release for 1.8.

**Comment by pinkkoff** [comment]
Unfortunately,i am not a programmer... OH1 has not bad wiki, is OH2 has it too?

**Comment by OLibutzki** [comment]
The reason is that Java8 introduced Iterable.forEach. This method is in conflict with Xtext/Xbase's API.

**Comment by kaikreuzer** [comment]
@OLibutzki Good point! What is the official workaround for this? Not using forEach at all...?

**Comment by udo1toni** [comment]
That's strange, because I'm using forEach and it works as expected, even under Java 8...

**Comment by OLibutzki** [comment]
@kaikreuzer Xtend has a problem if you use a Java 8 compiler to compile Java 6 or Java 7 code. Xtend checks the Java-API and Iterable.forEach takes precedence over Xtend's IterableExtensions.forEach. The Xtend compiler generates Java code that calls Iterable.forEach which is not present in Java 6/7. You have to use Maven toolchains in order to compile to the corresponding JDK's API, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=438764

Anyway, openHAB interprets the Xbase expression instead of compiling them to Java code. In this scenario the Scope Provider checks the API at runtime and I would expect that it works out-of-the-box. Instead of IterableExtensions.forEach Iterable.forEach shoudl be called in Java8, but that shouldn't be a problem.

I assume that this is a problem in the openHAB specific interpreter implementation. Maybe it always fails if you call forEach at an Iterable of Items?

@udo1toni Can you post the code that works as expected?

**Comment by udo1toni** [comment]
Sure :)
e.G. this one:
`GS_Bath?.members.forEach(Shutter|Shutter.sendCommand(UP))`
where GS_Bath is a Group of Items - obvious ;)

**Comment by OLibutzki** [comment]
@udo1toni Thanks, just to make sure it doesn't depend on the syntax:
Does this work as well?

`GS_Bath?.members.forEach[sendCommand(UP)]`
