### ISSUE TITLE
Classic UI error message when loading an image

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab#3773]
The following appears in the chrome's console:

>GET https://192.168.1.2:8443/%22https://192.168.1.2:8443/classicui/WebApp/Design/Img/loader-gray-100x12x2.png%22 404 (ProxyServlet: /%22https://192.168.1.2:8443/classicui/WebApp/Design/Img/loader-gray-100x12x2.png%22)

The unescaped version of the URL is:
>https://192.168.1.2:8443/"https://192.168.1.2:8443/classicui/WebApp/Design/Img/loader-gray-100x12x2.png"

**Comment by brettyj** [comment]
I'm closing this as I can see it's been raised here https://github.com/openhab/openhab/issues/2900

**Comment by watou** [comment]
This identical problem exists in the [demo for WebApp.net](http://demo.webapp-net.com/#_Home) in its latest version (this is apparently the final version since it's now [over six years since 0.5.2](http://trywebapp.net/changes.php)).  I think the underlying problem is in code we should not modify ourselves, and since it's been years since it was updated, I am going to mark this "wontfix".
