### ISSUE TITLE
External authentication also requires credentials for internal network

### ISSUE THREAD

**Issue by stefaanbolle** [openhab/openhab#3781]
Below problem occurs with 1.7.1 and also with 1.8.0
I've setup openhab with ssl and authentication. I have a correct users.cfg file which is working.
When I try to connect from the internal LAN (using ssl - 8443 or no ssl - 8080) the credentials are always asked.
Possibly a bug?

Below my openhab.cfg settings
  security:option=EXTERNAL
  security:netmask=192.168.1.0/24

**Comment by semperor** [comment]
I can confirm that on 1.8.0 on Linux. I tried `security:netmask=192.168.1.0/24` and `security:netmask=255.255.255.0`. Both didn't worked.

**Comment by steve-bate** [comment]
I just upgraded from 1.7.1 to 1.8.2 and I'm seeing the same problem.

**Comment by steve-bate** [comment]
Apparently the issue is caused when the browser decides to send an IPv6 address for a specified hostname. In my case, the hostname is resolved using mDNS and apparently is resolved to an IPv6 address. If I specify the IPv4 address explicitly, then the authentication is bypassed. This isn't an ideal solution, but it's better than needing to enter credentials every time I request the page from my LAN.

**Comment by steve-bate** [comment]
It looks like the following code might work to handle both IPv4 and IPv6 subnet range checking.

https://github.com/edazdarevic/CIDRUtils/blob/master/CIDRUtils.java

**Comment by steve-bate** [comment]
After more investigation, I found that the security:netmask has an undocumented feature that allows multiple netmasks to be defined (IPv4 and/or IPv6). I used that feature to specify both an IPv4 and IPv6 netmask for my LAN to bypass authentication.
