### ISSUE TITLE
GPIO Binding does not report inputs with Raspbian Jessie

### ISSUE THREAD

**Issue by sheppy99** [openhab/openhab#3896]
Since updating my Raspberry Pi 2 from Wheezy to Jessie, Contact items no longer work. Switch Items Work, Debug logging doesn't show anything obvious. Changing back to Wheezy with no other changes apart from the SD Card restores full functionality.
##

**Comment by etlmwwn** [comment]
Identical issue (also noted in [this ](https://community.openhab.org/t/raspian-jessie-gpio-input/3448 )thread).

BUILD: 

- OS: jessie  - Linux raspberrypi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux
- HW: Raspberry Pi  B+
- java version "1.7.0_40"
- Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
- Java HotSpot(TM) Client VM (build 24.0-b56, mixed mode)

- ii  openhab-addon-binding-gpio     1.8.0                      all          openHAB GPIO Binding
- ii  openhab-addon-io-gpio          1.8.0                      all          openHAB GPIO IO Module
- ii  openhab-runtime                1.8.0                      all          openHAB Distribution


On the OS Level you can read the different state if the GPIO Pins as follows: 

cat /sys/class/gpio/gpio23/value 

The are no changes to the openhab.log or to the assigned "contact".

The only time openhab reads the GPIO status, is once on start up, or if you do the following (just to kick openhab into reading the jar file again):

sudo mv org.openhab.io.gpio-1.8.0.jar org.openhab.io.gpio-1.8.0.jar.bak
GPIO access is lost
sudo mv org.openhab.io.gpio-1.8.0.jar.bak org.openhab.io.gpio-1.8.0.jar
GPIO access is restored, and the GPIO Pins are read correctly by openhab, once only, then the GPIO pins are not read again.

**Comment by sheppy99** [comment]
Thanks for the reply, is this binding still maintained? The workaround in the thread above using a combination of an older binding and a modified io file does work, so maybe the binding files and instructions need changing to this one going forward? Maybe AlejandroGuirao would be interested in contributing his fix to the official repository?
Apologies if I have the hierachy wrong, I'm not sure how the maintainers / moderators work

**Comment by AlejandroGuirao** [comment]
There are basically two problems with this binding:

1.  The included JNA jar is outdated and does not include the native .so libraries. Depending on the installed version of these native libraries the java part blocks trying to allocate a structure (end therefore there ). The solution is to build the gpio binding with an actual JNA jar which includes the needed native libraries so there is no version conflict.

 2.  To allow other users to access the /sys/class/gpio file system it belongs to the group gpio. Thus adding the user openhab to the gpio group allows openHAB to access the gpio. When a new gpio pin is reserved an udev script changes the group ownership and permissions. The gpio binding must wait a few milliseconds in order for this script to finish. Otherwise there is a race condition and the binding tries to write to the pin before is is writable for the gpio group. The solution is to include a small wait time in the method that reserves the pin. Afterwards the pin is checked for read permissions and throws an exception if not.

As a general issue I would like to suggest using Pi4J instead of JNA for accessing the gpios. The main reason is that Pi4J relies on hardware interrupts when waiting for pin value changes which is more effective than the polling method used in the gpio binding.

**Comment by MagnusChrist** [comment]
My fresh jessie distribution together with the gpio-binding and openhab 1.8.1 installation does not work out of the box. Now with the JAR files (io, binding) of Alejandro Guirao I found the solution to the problem. In particular, I find his approach very good, instead polling interupting to use. Thx Alejandro Guirao, very good job!

**Comment by watou** [comment]
I am thinking of writing a binding that exposes the features of the [Pi4J library](http://pi4j.com/), allowing access to GPIO pins on supported Raspberry Pi models and the Compute Module, PiFace communication and control over SPI, as well as retrieving system and network information.  The binding would require that the openHAB runtime is run as the root user, but would otherwise be fully self contained.  Is anyone else working on this?

**Comment by AlejandroGuirao** [comment]
I have already written such a binding (the org.openhab.io.pi4j part of it to be specific). Although there was not much to do because Pi4J already has a such a binding which i modified in just one point as to allow non-root access (Pi4J 1.1.snapshot). What i have not done up to now is to modify the binding.gpio package to use org.io.pi4j.

**Comment by watou** [comment]
Great!  Would it be better to create a new pi4j binding instead of modifying the gpio binding, so you wouldn't have to be concerned with backward compatibility and you could expose more of what Pi4J provides?

Also, would it make sense to have such a binding use the existing OSGi services exposed by pi4j-service and use a `Bundle-NativeCode` instruction there so that the pi4j-service is a complete, installable bundle, (like I did [here](https://github.com/watou/openhab-pi4j/tree/bundle-nativecode)) instead of an org.openhab.io.pi4j package that adds another layer?

**Comment by watou** [comment]
> i modified in just one point as to allow non-root access (Pi4J 1.1.snapshot)

So it no longer opens /dev/mem?  Does that limit what Pi4J is able to do?

**Comment by AlejandroGuirao** [comment]
I just repackaged pi4j and added an an Activator class which registers the services and, most important, check the user and if its not root activates non privileged access. This forces pi4j to access /dev/gpiomem which doesn't need root access. The backside is that some things like pwm do not work. See http://www.savagehomeautomation.com/projects/pi4j-now-supports-non-privileged-access-no-more-rootsudo.html
I uploaded the code here: <link>https://github.com/AlejandroGuirao/openhab-pi4j</link>

**Comment by sheppy99** [comment]
@AlejandroGuirao is the syntax of the items for use with this binding the same as with the GPIO Binding? 
I'm using the earlier fixed V1.7 version of GPIO on Jessie, and I see that 2 of my GPIO Pins are posting several updates per second when I view the log in debug mode. I've put a meter across the Pins and can't find any reasons for this so I think it may be a bug that I can get around by using Pi4J.

**Comment by LeoVe** [comment]
I'm using OpenHAB and bindings v 1.8.2 (z-wave 1.9.0) on a RPi 3 with the newest Raspbian/Jessie distribution and packages, I seem to have the same problem with the GPIO input?

How to resolve this one?

**Comment by 9037568** [comment]
Closed via PR #4517
