### ISSUE TITLE
Web page refresh too fast

### ISSUE THREAD

**Issue by dariocdj** [openhab/openhab#3903]
I think I've a sensor that update his state too fast causing oh to reload webpage after a couple of seconds and scrolling to top of page. How to avoid this? Habdroid running fine. Thanks

**Comment by watou** [comment]
The only way I'm aware of to avoid the known scroll-to-top bug is to have the page of the sitemap that the item appears on be short enough that it doesn't scroll.  Since previous reporting of this issue concluded with "wontfix," please close this issue and continue further discussion at https://community.openhab.org.

**Comment by dariocdj** [comment]
Ok, i understand and hope that you fix it, thanks

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
