### ISSUE TITLE
MQTT binding should be installable from OH2

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab#3925]
The MQTT binding 1.9 combined with MQTT io transport 1.9 is working well in openHAB2.
So this binding should be installable from Paper UI in OH2.

Please note that I did not test the MQTT event bus feature.

**Comment by lolodomo** [comment]
Don't forget the mqqt.cfg file.

**Comment by watou** [comment]
> Don't forget the mqtt.cfg file.

Yes, thanks, I'm working on that now, but I have a question for @kaikreuzer: 

The openhab-transport-mqtt feature is the one that needs to be configured with broker(s), etc., so should the mqtt.cfg file be installed by that service instead of the binding?  I am also providing a mqtt-persistence.cfg for the MQTT persistence service, is that correct?

Until you say otherwise, I will proceed with a PR that adds mqtt.cfg like the other OH1 bindings, but it seems inconsistent to not leave MQTT configuration the responsibility of the openhab-transport-mqtt feature.

**Comment by lolodomo** [comment]
Please note I provided no feedback for MQTT persistence. I am not using it.

**Comment by lolodomo** [comment]
OK in OH2 snapshot 111

**Comment by watou** [comment]
Excellent, thanks!
