### ISSUE TITLE
Zip files not created during build

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab#3934]
When building out of the latest master since the upgrade to 1.9 the expected zip files are not created.

In 1.8, these were created:

    01/23/2016 01:15 PM  85,858,138 distribution-1.8.0-SNAPSHOT-addons.zip
    01/23/2016 01:15 PM     666,350 distribution-1.8.0-SNAPSHOT-demo.zip
    01/23/2016 01:15 PM 112,934,926 distribution-1.8.0-SNAPSHOT-designer-linux.zip
    01/23/2016 01:15 PM 113,148,978 distribution-1.8.0-SNAPSHOT-designer-linux64bit.zip
    01/23/2016 01:15 PM 112,632,811 distribution-1.8.0-SNAPSHOT-designer-macosx64.zip
    01/23/2016 01:15 PM 113,234,621 distribution-1.8.0-SNAPSHOT-designer-win.zip
    01/23/2016 01:15 PM   3,028,173 distribution-1.8.0-SNAPSHOT-greent.zip
    01/23/2016 01:14 PM  37,770,538 distribution-1.8.0-SNAPSHOT-runtime.zip
    01/23/2016 01:15 PM  37,321,062 openhab-runtime-1.8.0-SNAPSHOT.deb

**Comment by watou** [comment]
The master branch no longer builds distribution files, but you can usually find build results in each project's target directory. As this is working as expected, I will close this issue, but please re-open if there is an actual bug in the build process not yet mentioned.  Thanks.

**Comment by 9037568** [comment]
What's the process for getting a working application, now that building the
application doesn't build the application?

None of the files needed can be found after running the build. (eg.
start.sh/start.bat, etc. etc.)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by watou** [comment]
> What's the process for getting a working application, now that building the
application doesn't build the application?

You can build a full OH1 distro by checking out the 1.8 branch and building that.  You can get addons from the master branch by building that.

**Comment by greenoid** [comment]
What's the purpose of not building the zip files and debian package in master anymore? Saving time in mvn install? Could you please document that change in the README? It took me days to get here and see this in on purpose. I just want a non standard /contributed binding in my OpenHAB. I didn't wanted to compile it initially, I didn't wanted to develop or enhance it, just use it. Now I'm in th state of compiling and merging and developing and first thing I learn is, I'm stuck because of this non documented change and have to learn some branching in git too because master is not good enough.

How about a goal or stage in Maven where these packages (zip & deb) are build which are not part of the install goal? So one could produce them only if wanted?

**Comment by greenoid** [comment]
I could build a OH1 distro with contributed bindings for Raspbian as 1.8.3-SNAPSHOT, good, works.

How is it suppoed to be: If there is a 1.10.0 comming, will 1.9.x produce deliverables again?

**Comment by 9037568** [comment]
There's no plan to ever produce deliverables in 1.x.y again, as far as I'm
aware.
You should probably move this discussion to the community forum...

**Comment by watou** [comment]
> There's no plan to ever produce deliverables in 1.x.y again

There is a 1.8.3 maintenance released planned that I'm aware of, but I don't know of any others considered at the moment.
