### ISSUE TITLE
MiOS Action - Missing variableSet call 

### ISSUE THREAD

**Issue by dodger777** [openhab/openhab#4009]
http://<miosIP>:3480/data_request?id=variableset&DeviceNum=<deviceID>&serviceId=urn:micasaverde-com:serviceId:DoorLock1&Variable=<VariableToSet>&Value=<Value>

This is changing a variable value in MiOS.

**Comment by mrguessed** [comment]
As it turns out, the equivalent of the MiOS `variableset` URL call is already accessible via the existing MiOS Binding Action, via a pre-defined serviceId that Micasaverde exposes.

The technique requires the addition of a single Item declaration over what the MiOS Item Generator produces (listed below) and the rest can be done with the standard Action decl.

**Item declaration**
```
Number   MiOSGateway "ID [%d]" {mios="unit:house,device:0/id"}
```

**Rule declaration**
```
rule "Test MiOS SetVariable"
when
    Time cron "0/10 * * * * ?"
then
    sendMiosAction(MiOSGateway, 'HAGateway/SetVariable',
                   newArrayList('DeviceNum' -> GarageDeadboltId.state.toString,
                                'Service' -> 'urn:micasaverde-com:serviceId:DoorLock1',
                                'Variable' -> 'sl_UserCode',
                                'Value' -> 'UserID="Unknown" UserName=""'))
end
```

**Notes**
* In my case, "GarageDeadboltId" resolves to the const 189, as generated by the MiOS Item generator, so I could inline that value instead.
* I push a `Value` that I know will parse correctly when it's sent back from MiOS to openHAB.

**Comment by mrguessed** [comment]
@dodger777,
Since this is available via the build in components, I'm planning to close out this Issue.  If you feel strongly otherwise, let me know.

**Comment by dodger777** [comment]
@mrguessed 
no problem with me. I will test that when i will have the time. Thanks!
