### ISSUE TITLE
RFXCOM wiki documenation about using hex values

### ISSUE THREAD

**Issue by ivanfmartinez** [openhab/openhab#4078]
I was updating the wiki for rfxcom and found the part that says the device id are in hex and should be converted : 

https://github.com/openhab/openhab/wiki/RFXCOM-Binding#getting-the-correct-decimal-deviceid-number

All devices that I have used are showing values in decimal.

In the binding code I did not find any printing in hex for the sensor Id.

This wiki information are still valid ?

**Comment by digiltd** [comment]
Hi. I added that bit about Hex to Dec originally.

Can I ask when you first installed and used the RFXcom binding?

For me, for every RF compatible device I wanted to add, it would always give the Id as Hex. This included PIRs, wall switches, socket dimmers, thermometers, socket switches and lightbulb bayonet switches.

Though I have just turned on the rfxcom debugging and you are correct that they now are now being reported in the correct Dec format.

So perhaps it was a change in the binding at some point between then and now. 

Not being 100% sure that it has been changed I am reluctant to remove it completely. So I will change the wording so that it more something to look out for and be aware of.

**Comment by steve-bate** [comment]
@digiltd, is the documentation updated? Can we close this issue now?

**Comment by digiltd** [comment]
It is, and yes you can close.

**Comment by steve-bate** [comment]
Thanks. Closed.
