### ISSUE TITLE
[tcp] NullPointerException

### ISSUE THREAD

**Issue by ElectricCraft1** [openhab/openhab#4380]
Raspbian Jessie,  latest oh2 snapshot, tcp 1.8.2.

Binding doesnt load on initial oh2 startup.  Can sometimes get it to load if a change is made to the tcp.cfg file, while oh2 is running.

logs can be found at:

https://community.openhab.org/t/tcp-binding-under-oh2/6902

**Comment by watou** [comment]
Please try the 1.9 binding from Cloudbees that is more likely to work with OH2.

**Comment by ElectricCraft1** [comment]
can you provide a link?

**Comment by watou** [comment]
I [see](https://community.openhab.org/t/tcp-binding-under-oh2/6902/18?u=watou) you found it, but FTR the 1.9 bindings are [here](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/).

**Comment by ElectricCraft1** [comment]
how to install?  just put it in addons like before?  did that then did a bundle:refresh, then bundle:list and it still shows 1.8 binding

**Comment by kaikreuzer** [comment]
Then please first do a bundle:uninstall of the 1.8 binding first!

**Comment by ElectricCraft1** [comment]
how?

**Comment by ElectricCraft1** [comment]
then how to install new?

**Comment by kaikreuzer** [comment]
drop in the addons folder

**Comment by ElectricCraft1** [comment]
how do i uninstall the 1.8?  i already deleted it from the addons folder

**Comment by kaikreuzer** [comment]
bundle:uninstall in the console

**Comment by ElectricCraft1** [comment]
kai

i appreciate the help, but i have to say, and this is for a lot of new people.....we dont know how to do all this.  i figured out it is 

bundle:uninstall 10

which i got from the list, but most of us have no clue, me included.  ao please remember when we are asking for help, we may need aome hand holding, just until we get comfortable.

**Comment by ElectricCraft1** [comment]
and on that note:

i uninstalled the bundle, have dropped the 1.9 binding called qith snapshot at the end.  i reatarted the server, refreshed the bundle list, and the new tcp bindle is not listed.  is there anything else i need to do?

**Comment by kaikreuzer** [comment]
> please remember when we are asking for help, we may need aome hand holding, just until we get comfortable.

Yes, you are fully right, sorry for being so short-spoken before and not really helpful - as I was busy with other stuff, I probably should better not have responded at all and come back to it at a better time.

I fully understand that this is all complex to get into, especially since there isn't yet documentation on openHAB 2 for starters. We are working on this now and the situation will hopefully be much much better soon.

>  is there anything else i need to do?

According to your post in the forum, this question is now obsolete, right? I would expect the bundle to have turned up as expected. If this is the case, please close this issue again. Thanks!
