### ISSUE TITLE
Contact does not accept AJAR state, needed to use the proper icon

### ISSUE THREAD

**Issue by rvfh** [openhab/openhab#4418]
## Expected Behavior
* a "Contact" can be either OPEN, CLOSED or AJAR, as the default icons set suggests (contact, garagedoor)
* updating a Contact state to AJAR should thus be accepted

## Current Behavior
* I tried both REST and MQTT and in both cases OPEN and CLOSED are accepted but AJAR is rejected

## Possible Solution
* accept the AJAR state for Contacts

## Steps to Reproduce (for bugs)
* post a AJAR value to a contact using the REST or MQTT interfaces

## Context
* trying to display a contact as either open, closed or ajar

## Your Environment
* Version used: openHAB 1.8.3
* Environment name and version: any
* Operating System and version: Ubuntu 16.04

**Comment by watou** [comment]
The Contact item in openHAB can have the states OpenClosedType and UnDefType (see [here](https://github.com/openhab/openhab/blob/1.8/bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/items/ContactItem.java#L36)).  You can either update the item to `UnDefType.UNDEF` to indicate neither open or closed is correct, or use a different item type, like a Rollershutter or String item.  

Since openHAB 1.x core is now frozen, these sorts of core changes would not be considered, and thus I will close this issue (don't shoot the messenger!).  Consider discussing this at community.openhab.org or at the Eclipse SmartHome forum.

**Comment by rvfh** [comment]
Yep I have worked around this so far by using a String.

Unfortunately, setting a contact to UNDEF gives me a grey 'no info' icon, and not the nice AJAR icon, so it would be great if AJAR was available in openHAB 2.0.

BTW, `mosquitto_pub -t first_kitchen_main_temperature -m UNDEF` works and solves an old issue of mine (temperature sensor being damaged), thanks a bunch! I had tried NULL, UNDEFINED, UNKNOWN, UNINITIALIZED...
