### ISSUE TITLE
Problem running 1.0 binding org.openhab.binding.mpower on openhab2

### ISSUE THREAD

**Issue by Chanete** [openhab/openhab#4421]
Hi, I'm trying to use this binding (I'm not the author, but I've been unable to contact him) which was running smoothless in openhab 1 but it doesn't start in OH2. I get this error:

[ERROR] [org.openhab.binding.mpower ] - FrameworkEvent ERROR - org.openhab.binding.mpower
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.mpower [193]
Unresolved requirement: Require-Bundle: org.apache.commons.httpclient

can anyone give a clue on how to solve it??

I'm stuck in a dead-lock. I need openhab2 to use part of the bindings I need because I have things not supported in OH1 (Netatmo Thermostat) but I have a lot of ubiquiti mpower wifi plugs that work perfect in OH1 but no way to start the plugin in OH2.

Thank's!!

**Comment by watou** [comment]
Try removing [this line](https://github.com/magcode/openhab/blob/master/bundles/binding/org.openhab.binding.mpower/META-INF/MANIFEST.MF#L35) and rebuilding the binding.  If you are [this poster](https://community.openhab.org/t/does-anyone-have-this-binding-org-openhab-binding-mpower/9900/2?u=watou), it looks like you are able to build the binding.

Since the binding is not part of this repo, please continue the discussion at https://community.openhab.org.  Thanks!

**Comment by Chanete** [comment]
Yes, It's me! 
I'll try. Thanks!
