### ISSUE TITLE
[Weather] barometric pressure unit conversion to inches non-functional

### ISSUE THREAD

**Issue by dzimmanck** [openhab/openhab#4466]
## Expected Behavior
When a Pressure_Inches item is created, expected behavior is to return a number with pressure converted to inches of Mercury.

Number   Pressure_Inches  "Pressure [%.2f in]"    {weather="locationId=home, type=atmosphere, property=pressure, unit=inches"}

So, if the pressure is currently 760mm, I expect Pressure_Inches to be 29.0.

## Current Behavior
Returns number in mm still

## Steps to Reproduce (for bugs)
Should be simple to reproduce.  Simply add the Pressure_Inches item described above and add to your sitemap.

## Context
Provides support for countries still using the imperial system of measurement where inHg is a more common way to display pressure.  (I know, I wish we were metric too).

## Your Environment
This was a fresh install on a Windows PC on 6/15/2016.
OpenHAB 1.8.3
org.openhab.binding.weather-1.8.3
Windows 10

**Comment by watou** [comment]
Please have a read through [this thread](https://community.openhab.org/t/yahoo-weather-api-returning-bad-value-for-pressure/9537), and if it is the same issue (bad data from Yahoo weather provider), please close this issue since it is bad data from the source.  Otherwise, please add your relevant openhab.cfg lines (obscuring any private information).

**Comment by dzimmanck** [comment]
Closing bug.  Appears to be an issue with bad data fro Yahoo, not OpenHAB.
