### ISSUE TITLE
HABDroid does not recognize &nbsp;

### ISSUE THREAD

**Issue by markrad** [openhab/openhab#4531]
If one uses ```&nbsp;``` in a label element in the sitemap, it is honored on the website. However, in HABDroid it displays the actual characters ```&nbsp;```

I expected it to replace them with spaces just as a web renderer would do.

HABDroid v1.8.0.2

**Comment by watou** [comment]
> I expected it to replace them with spaces just as a web renderer would do.

The Android client doesn't use a web renderer for sitemaps, so embedded HTML (including HTML entities) will come through without interpretation.  It is perhaps a bug in the Classic UI that labels are not escaped before rendering via the servlet.

**Comment by markrad** [comment]
But this makes it basically impossible to indent a line such that it would display as:
```
Maximum Temperature:                       99F
    At:                                    16:34
```
If you use spaces HABDroid is happy but the web browser collapses them but if you use \&nbsp; - well you know what happens on HABDroid but it looks fine on the webpage. Seems like something people would use. I'm not asking for HTTP parsing but this one simple piece of text replacement would seem to be easy to do for a decent return.

**Comment by watou** [comment]
I am going to close this issue here, as in any case the issue would not be addressed in this repo.  I think that it is along the same line as https://github.com/openhab/openhab.android/issues/163 and https://github.com/openhab/openhab.android/issues/50, but the subject might need to be addressed at a core level (Eclipse SmartHome) -- what is the official interpretation of label text in sitemaps?  Perhaps further discussion in either the [ESH forum](https://www.eclipse.org/forums/index.php?t=thread&frm_id=271) or [openHAB forum](https://community.openhab.org).
