### ISSUE TITLE
Add UPB binding to OH2

### ISSUE THREAD

**Issue by watou** [openhab/openhab#4811]
The UPB binding has been shown to work properly under openHAB 2 (by @DaAwesomeP).  So it should be added.

See https://github.com/openhab/openhab2-addons/issues/1461

It can be configured with `refresh` (optional), `port` and `network`.

@cvanorman May I use your real name on the UPB binding in openHAB 2 (if so, what is it?), or would you prefer to have no author credit at all (the only two options)?

**Comment by cvanorman** [comment]
My full name is Chris Van Orman and, yes, you may use it.

**Comment by DaAwesomeP** [comment]
@cvanorman just want to thank you again for the binding. Today I successfully set up dummy links to control OH switch states.

**Comment by watou** [comment]
I have a branch ready to add the binding to OH2.  Only thing left afaik is @cvanorman's preference on author attribution.

**Comment by DaAwesomeP** [comment]
@watou if the binding will be mapped to any "things," remeber that there are two types: devices and links.
````
Switch Link20 "Link 20" {upb="id=20 link=true"}
Dimmer Link17 "Link 17" {upb="id=17 link=true"}
Switch Device2 "Device 2" {upb="id=2}
Dimmer Device12 "Device 12" {upb="id=12}
```

**Comment by watou** [comment]
OK!  Thanks Chris!

**Comment by watou** [comment]
No Things in OH1 bindings!

**Comment by DaAwesomeP** [comment]
Thank you!

**Comment by gmoneyman** [comment]
I am stuck. I decided to upgrade to OpenHab 2.0 because of the myopenhab change and the future with direct communication with Amazon Alexa.

I used the Openhabian image so I headless using Karaf which I am not that familiar. The problem is with the UPB binding or the new image communication with the USB port or the binding. The owfs.config is using /dev/ttyUSB0 and so is the upb.cfg file.
This is what the lsusb looks like:


[08:19:51] pi@openHABianPi:~$ sudo lsusb
[sudo] password for pi:
Bus 001 Device 004: ID 17dd:5500
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

I can get figure out where the logs are stored but I took a screen shot of the log.

Someone help……


![screenshot-1](https://cloud.githubusercontent.com/assets/18370275/21352837/5607fb02-c691-11e6-91f9-d991cf4c970f.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/18370275/21352838/560ecca2-c691-11e6-8a64-e4635c9d4087.png)

**Comment by watou** [comment]
@gmoneyman: Do you see your device `/dev/ttyUSB0` in a directory listing?

```bash
ls -l /dev
```
What are its ownership and permissions?  Could you paste your upb.cfg file here exactly as it is on disk?

**Comment by gmoneyman** [comment]
No, it is not. The ttyS0 is there and I tried with that in my upb.cfg file
and it did not work.

[image: Inline image 1]
The upb.cfg reads:

port=/dev/ttyUSB0
network=17

**Comment by DaAwesomeP** [comment]
This sounds related to my issue in #4814. I could not get the OH2 binding to see any configuration or connect to the right serial port, resulting in an error.

**Comment by watou** [comment]
> Do you see your device /dev/ttyUSB0 in a directory listing? / No, it is not.

You must first make sure you have the device name for a working serial port on your machine that is connected to your hardware before the binding will be able to work with it.  There might be other forums or maybe https://community.openhab.org that can help with that part.
