### ISSUE TITLE
GPIO binding: Switch to pi4j

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab#4976]
I'd like to suggest extending the GPIO binding to support [pigpio](http://abyz.co.uk/rpi/pigpio) as an easier way to use GPIOs on the Raspberry Pi. The GPIO binding creates a lot of problems for users as it needs system settings modifications, which differ from system to system, resulting in [numerous forum discussions](https://community.openhab.org/tags/gpio). pigpio is a small daemon providing GPIO functionality without elevated permissions of any kind. *At first sight* this sounds like a great deal.

What do the previous authors think? @danielbarron42 @9037568 @Speederc @dpslavov

**Comment by watou** [comment]
I would be curious to see how pigpio compares to [pi4j](http://pi4j.com/) in terms of range of supported systems, functionality possible without needing elevated privileges, etc.

**Comment by ThomDietrich** [comment]
I have no experience with one or the other. pi4j also looks promising.
**However:** for me the most important requirement would be to make usage easier, meaning lifting the privileges problem... http://pi4j.com/faq.html#permissions

**Comment by watou** [comment]
Absolutely agree that not having to run as root is very important for usability.  That seems to have been remedied (see [here](http://www.savagehomeautomation.com/projects/pi4j-now-supports-non-privileged-access-no-more-rootsudo.html)).

**Comment by ThomDietrich** [comment]
I actually know about this enhancement. It's less related to pi4j and more to Raspbian - and that's the problem. I didn't take the time to investigate myself but it seems like the base I'm using for openHABian [does not create a gpio](https://github.com/openhab/openhabian/issues/39#issuecomment-267817826) group. However I'm sure this can be solved, I just will have to look into that.

One solution would be to not depend on the gpio group by the use of pigpio but I have to admit, that pi4j offers some nice features. The important question now: Would you like to look into that?

**Comment by watou** [comment]
It would be a fun project to make an openHAB 2/ESH binding against Pi4j.  The things/channels would be pretty obvious.  I will think about that!

Meanwhile, here is a related issue: #4583

**Comment by ThomDietrich** [comment]
You totally made your point plus pi4j seems like a great base for that binding. As I said, I'll have to look into the problem from openHABian's side.
I've renamed the issue. Would be great to hear news soon ;)

**Comment by watou** [comment]
@ThomDietrich would it be OK if you close this issue and open a new one in openhab2-addons requesting a new OH2 binding that expresses functional requirements like these:

* Event-driven GPIO changes (no polling)
* Logical pin numbering system that does not require any openHAB reconfiguration when moved to new hardware
* Package any required native libraries in the binding using the OSGi `Bundle-NativeCode` directive so no prior native installation is required
* Functions by having added any needed privileges to openhab user account instead of requiring openHAB to be run as root (whenever possible)
* Support multiple common platforms where GPIO access is possible, with ability to add future platform support when available
* Clear, usable, sensible Things and Channels

I think the OH1 GPIO binding should be left in its current state and a new OH2 binding written that meets the above requirements.

**Comment by ThomDietrich** [comment]
I fully agree this should be moved over as this will effectively be a new binding anyhow. I'll close this one, you could create the new one, leading with your list of requirements ;) Thanks for looking into that topic!
