### ISSUE TITLE
[Netatmo] Config description validation exception occured

### ISSUE THREAD

**Issue by sebplorenz** [openhab/openhab#4991]
## Context
Using PaperUI I added my Netatmo station to openhab. For the id I added its MAC address with lower-case letters: 70:ee:50:27:84:8b. Everything was fine and the station was being synced.
But when I tried to change the refresh interval of the Main Station I got a 404 - Bad Request message in the client. The log contained the following error:

``
Config description validation exception occured for thingUID netatmo:NAMain:872aaf22:70ee5027848a - Messages: {equipmentId=The value 70:ee:50:27:84:8b does not match the pattern [0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}.}
``

Changing the Netatmo MAC address to capital letters fixed the error.  But this should be done automatically when creating the Thing.

## Possible Solution
This could be fixed either by:
- uppercasing the MAC address when it is entered or by
- changing the pattern to also accept lower-case letters.

I could do the fix if someone tells me what the desired behaviour is. @clinique?

**Comment by watou** [comment]
If the ultimate consumer of the equipment ID accepts lowercase a-f, then the pattern should be

```
\p{XDigit}{2}:\p{XDigit}{2}:\p{XDigit}{2}:\p{XDigit}{2}:\p{XDigit}{2}:\p{XDigit}{2}
```
(See [this](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html).)

But if this issue is about the Netatmo 2.0 binding, the issue here should be closed and opened [here](https://github.com/openhab/openhab2-addons/issues).

**Comment by sebplorenz** [comment]
Thanks for the hint.
