### ISSUE TITLE
Stop video/image downloading when active page is switched at web gui

### ISSUE THREAD

**Issue by eschava** [openhab/openhab#611]
I have Image tag with reference to mjpeg stream from IP camera
I've noticed after I change active frame (e.g. go back to the main frame) image is still downloaded (because img is only hidden, not removed from html page)

**Comment by teichsta** [comment]
since there won't be any effort to implement new features into 1.x version of classicui i'd like to close this issue. Can you please have a look at the new BasicUi (maintained at openhab/openhab2) whether this issue still applies? If yes please discuss your feature-request at https://community.openhab.org before entering an issue here.
