### ISSUE TITLE
Modbus RS485

### ISSUE THREAD

**Issue by fmabreu** [openhab/openhab#626]
When used in two or more slave RS485 bus of a read error of the serial since the poll and the same for all slave. Every poll the serial and opened and closed connection. I think the connection to be binding and not to the slave

**Comment by nickma82** [comment]
@fmabreu could you please post your openhab.config?

**Comment by kvakanet** [comment]
Hello!
 OpenHAB 1.7.0 
When I have one device on the bus rs485 uses the parameters 9600n2 openhab then sends the request, but the device does not respond.
```
modbus:serial.seapp_version.connection=/dev/rs485bus:9600:8:none:2:rtu
modbus:serial.seapp_version.id=11
modbus:serial.seapp_version.start=46152
modbus:serial.seapp_version.length=2
modbus:serial.seapp_version.type=holding
```
 When I query the device via the parameter modpoll 9600n2 the device responds. (If I check with parameter 9600n1 is not responsible). When I change the settings of the device on the 9600n1 openhab normally works with device with config.
```
modbus:serial.seapp_version.connection=/dev/rs485bus:9600:8:none:1:rtu
modbus:serial.seapp_version.id=11
modbus:serial.seapp_version.start=46152
modbus:serial.seapp_version.length=2
modbus:serial.seapp_version.type=holding
```
When I add the bus to another device 9600n2 parameters, then writes openhab read errors.
```
2015-07-16 17:01:32.085 [ERROR] [w.m.io.ModbusSerialTransaction] - execute try 1 error: I/O exception - failed to read
2015-07-16 17:01:37.643 [ERROR] [i.modbus.io.ModbusRTUTransport] - Last request: 09 01 00 00 00 08 3c 84
2015-07-16 17:01:37.644 [ERROR] [i.modbus.io.ModbusRTUTransport] - failed to read: Error reading response
2015-07-16 17:01:37.645 [ERROR] [w.m.io.ModbusSerialTransaction] - execute try 1 error: I/O exception - failed to read
2015-07-16 17:01:43.199 [ERROR] [i.modbus.io.ModbusRTUTransport] - Last request: 09 01 00 00 00 08 3c 84
2015-07-16 17:01:43.200 [ERROR] [i.modbus.io.ModbusRTUTransport] - failed to read: Error reading response
2015-07-16 17:01:43.201 [ERROR] [w.m.io.ModbusSerialTransaction] - execute try 1 error: I/O exception - failed to read
2015-07-16 17:01:48.755 [ERROR] [i.modbus.io.ModbusRTUTransport] - Last request: 09 01 00 00 00 08 3c 84
```
My config:
```
modbus:serial.senka_out_01.connection=/dev/rs485bus:9600:8:none:2:rtu
modbus:serial.senka_out_01.id=9
modbus:serial.senka_out_01.start=0
modbus:serial.senka_out_01.length=8
modbus:serial.senka_out_01.type=coil
#
modbus:serial.seapp_version.connection=/dev/rs485bus:9600:8:none:1:rtu
modbus:serial.seapp_version.id=11
modbus:serial.seapp_version.start=46152
modbus:serial.seapp_version.length=2
modbus:serial.seapp_version.type=holding
```

**Comment by nickma82** [comment]
I'm not quite sure about that but I think this is the problem I mentioned a couple of weeks ago [here](https://groups.google.com/d/msg/openhab/0BtLVPpta9U/WY4Tx98LJ1wJ).

IMHO there is a need to change the [ModbusSerialSlave.java](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusSerialSlave.java#L32-L37), such that connection specific variables (`baud, dataBits, parity, stopBits, serialEncoding`) are instance variables of `ModbusSerialSlave` but not static. Because now every instance of `ModbusSerialSlave` is overriding the setup from every other instance.

Further the variables mentioned above should be bound to the actual physical port (`ModbusSerialSlave.port`) which should be a list of opened ports with their current setup. Depending on whether there is a new setup needed for the next transceive on a very port or not, it should be set up if needed only (e.g. if there is just one `.connection` setup for a `.port` there is no need to change anything after the initial setup).

If one is willing to implement that changes with me, please contact me.

**Comment by nickma82** [comment]
Just to note that, it potentially affects the following problems: 
https://community.openhab.org/t/modbus-binding-multiple-serial-masters/3383
https://community.openhab.org/t/modbus-serial-failed-to-read/3430
https://groups.google.com/d/topic/openhab/0BtLVPpta9U

**Comment by ssalonen** [comment]
Please test with the expiremental version, linked to [this forum thread](https://community.openhab.org/t/connection-pooling-in-modbus-binding/5246/12?u=ssalonen)
