### ISSUE TITLE
Listening Group Adress in KNX Binding seems broken

### ISSUE THREAD

**Issue by rklueber** [openhab/openhab#762]
Hi guys,

can someone please have a look on this issue.

I investigated further on this end. It seems only one Switch item is updated in OH. I did a dedicated set of items

test.items
Group gTest "Testitems"
Switch Test1 (gTest) { knx="7/1/1+7/1/2" }
Switch Test2 (gTest) { knx="7/1/2+7/1/1" }

If you send messages with ETS to the bus the following happens:
start condition in OH: Test1 and Tes2 are OFF, Both GA 7/1/1 and 7/1/2 are set to [0]
send in ETS 7/1/1->[1] : Switch Item Test1 is ON as expected
send in ETS 7/1/2->[0] : Switch Item Test1 is OFF as expected
send in ETS 7/1/1->[0] : Switch Item Test1 stays OFF as expected
send in ETS 7/1/2->[1] : Switch Item Test1 is ON as expected, Test2 stays OFF unexpectedly

I would expect with the above definition both Switch Items have always the same state when changes coming form the KNX bus.

Same issue other example:

// Steckerleisten
Switch Leiste_4A "4fach Kanal A"        <socket>   (gSteckleisten) { knx="<1/2/0+0/0/1" }
Switch Leiste_4B "4fach Kanal B"        <socket>   (gSteckleisten) { knx="<1/2/1+0/0/1" }
Switch Leiste_4C "4fach Kanal C"        <socket>   (gSteckleisten) { knx="<1/2/2+0/0/1" }
Switch Leiste_4D "4fach Kanal D"        <socket>   (gSteckleisten) { knx="<1/2/3+0/0/1" }
Switch Leiste_AA "2fach_A Kanal A"      <socket>   (gSteckleisten) { knx="<1/2/4+0/0/1" }
Switch Leiste_AB "2fach_A Kanal B"      <socket>   (gSteckleisten) { knx="<1/2/5+0/0/1" }
Switch Leiste_BA "2fach_B Kanal A"      <socket>   (gSteckleisten) { knx="<1/2/6+0/0/1" }
Switch Leiste_BB "2fach_B Kanal B"      <socket>   (gSteckleisten) { knx="<1/2/7+0/0/1" }
Switch Leiste_A "1fach_A"               <socket>   (gSteckleisten) { knx="<1/2/8+0/0/1" }
Switch Leiste_B "1fach_B"               <socket>   (gSteckleisten) { knx="<1/2/9+0/0/1" }
Switch Leiste_C "1fach_C"               <socket>   (gSteckleisten) { knx="<1/2/10+0/0/1" }

Switch  AllesAus           "Alles Aus"    <allesaus>      (All)   { knx="0/0/1" }

When 0/0/1 received OFF only on of the above listed items is set to OFF.
##

**Comment by maxpg** [comment]
I guess there is still no fix for that?

I think I have the same problem. Two items which have the same KNX group address to read the state from. It seems only one is updated.

**Comment by Snickermicker** [comment]
I might be wrong, but I guess the original problem looks strange.
@rklueber: I'm not sure though what you're trying to achieve.
Your config would result in Test1 showing the status of Test2 and vice versa.
Let me know if I am wrong :)
@maxpg: did this ever work before? I'm probably missing it: so what is the use case for two items depending on one status KNX group address? 
Cheers

**Comment by maxpg** [comment]
Don't know if it worked before, just tried it for the first time. I have the following use case.

I have a knx actor for my rollershutter. This can do the following:
- Local command: move rollershutter to position x. Address for ex. 1/1/1
- Global command (for automation programs): move rollershutter to position x. Adress for ex. 1/1/2
- Current rollershutter position: 1/1/3

The actor then does the following. When a local command is received then the global commands are blocked for a certain time.

For example, when I use a switch in a room, this is a local command. Global commands (my automation program) is blocked for some time. Lets come to openhab.

I have two items there:
- Rollershutter_Position
- Rollershutter_Automatic_Position

The first one I would like to use in my visualization. So when I move the rollershutter down using the smartphone it behaves the same as when I do this with a switch on my wall.

The second one is for my rules that move the rollershutters automatically. So I have two different addresses to set the position --> two items

But I only have one single address for my status. I thought this would be no problem, because when I say to both items they should read the state from 1/1/3 everything should be fine. In KNX I can also let several devices listen for a single address.

I am not sure if it should work this way or if this would be a new feature. But I think it would make sense to behave this way, so to allow to set the state of several items when a certain address is put on the KNX bus.

Markus

**Comment by Snickermicker** [comment]
The binding doesn't support this (to my knowledge). I guess I would use one of the two command addresses but not both. Your rules should work on either and you shouldn't see a difference.

**Comment by maxpg** [comment]
They will not work the same. If I only made use of the second item, then I would not be able to move the rollershutter with my smartphone if anyone has pressed the switch on the wall within the last hour before. I could make a workaround rule that updates the state of the second item whenever the state of the first item changes. However, I have 17 rollershutters and this would make my rules quite ugly.

Maybe I will have a look at the code of the KNX binding.

**Comment by kerry9842** [comment]
Hi,
I am newbie to KNX. I am trying to demonstrate below scenario:

There is two sensor

Sensor 1 - When sensor detected ON LED_1, LED_2 and LED_3
sensor 2 - When sensor detected ON LED_2, LED_3 and LED_4

So here LED_2 and LED_3 is common to both sensor group address.

How i can assign both Sensor group address to LED_2 and LED_3. 

Thanks & Regards,
Kerry

**Comment by 9037568** [comment]
Closing as abandoned. Please start a new ticket if this is still occurring in the latest release.
